/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 1
 * @maxItems 100
 */
export type Userids = [string, ...string[]];
export type Conversationshandled = number;
export type Firstresponsep50Seconds = number | null;
export type Firstresponsep90Seconds = number | null;
export type Messagessent = number;
export type Name = string;
export type Quickreplyshare = number | null;
export type Slabreaches = number;
export type Userid = string;
export type Workorderscreated = number;
export type Boolvalue = boolean | null;
export type Numbervalue = number | null;
export type Textvalue = string | null;
export type Active = boolean;
export type Category = string | null;
export type Departmentid = string | null;
export type Description = string | null;
export type Name1 = string;
export type Thumbnailurl = string | null;
export type AssetType = 'file' | 'link' | 'menu' | 'map' | 'form';
export type Url = string;
export type Validfrom = string | null;
export type Validuntil = string | null;
export type Active1 = boolean;
export type Category1 = string | null;
export type Departmentid1 = string | null;
export type Description1 = string | null;
export type Id = string;
export type Name2 = string;
export type Sendcount = number;
export type Shortcode = string;
export type Thumbnailurl1 = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "AssetType".
 */
export type AssetType1 = 'file' | 'link' | 'menu' | 'map' | 'form';
export type Url1 = string;
export type Validfrom1 = string | null;
export type Validuntil1 = string | null;
export type Active2 = boolean | null;
export type Category2 = string | null;
export type Departmentid2 = string | null;
export type Description2 = string | null;
export type Name3 = string | null;
export type Thumbnailurl2 = string | null;
export type Url2 = string | null;
export type Validfrom2 = string | null;
export type Validuntil2 = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "AuthorType".
 */
export type AuthorType = 'guest' | 'staff' | 'system' | 'automation';
export type Active3 = boolean;
export type Name4 = string;
export type Parentid = string | null;
export type Active4 = boolean;
export type Children = CategoryOut[];
export type Id1 = string;
export type Name5 = string;
export type Parentid1 = string | null;
export type Active5 = boolean | null;
export type Name6 = string | null;
export type Parentid2 = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "Channel".
 */
export type Channel = 'sms' | 'web' | 'whatsapp' | 'email';
export type Userid1 = string | null;
export type Id2 = string | null;
export type Key = string;
export type Name7 = string;
export type Id3 = string;
export type Name8 = string;
export type Position = number;
export type Done = number;
export type Id4 = string;
export type Name9 = string;
export type Position1 = number;
export type Total = number;
export type Comment = string | null;
export type Answeredat = string | null;
export type Boolvalue1 = boolean | null;
export type Id5 = string;
export type Itemid = string;
export type Numbervalue1 = number | null;
export type Outofrange = boolean;
export type Textvalue1 = string | null;
export type Answers = RunAnswerOut[];
export type Assignedname = string | null;
export type Assigneduserid = string | null;
export type Categories = ChecklistCategoryProgressOut[];
export type Comment1 = string | null;
export type Completedat = string | null;
export type Completedbyname = string | null;
export type Departmentid3 = string;
export type Departmentname = string;
export type Done1 = number;
export type Duedate = string;
export type Id6 = string;
export type Active6 = boolean;
export type Categoryid = string | null;
export type Id7 = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PmItemType".
 */
export type PmItemType = 'checkbox' | 'text' | 'number' | 'photo';
export type Label = string;
export type Maxvalue = number | null;
export type Minvalue = number | null;
export type Position2 = number;
export type Required = boolean;
export type Unit = string | null;
export type Items = ChecklistItemOut[];
/**
 * Drives a filter and a tag only — no behaviour differs (checklist structure spec §1.2).
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistKind".
 */
export type ChecklistKind = 'normal' | 'readings';
export type Missingrequired = string[];
export type Ondemand = boolean;
export type Outofrangecount = number;
export type Bytesize = number;
export type Contenttype = string;
export type Createdat = string;
export type Id8 = string;
export type Itemid1 = string | null;
export type Uploadedbyuserid = string | null;
export type Url3 = string;
export type Photos = RunPhotoOut[];
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "Shift".
 */
export type Shift = 'am' | 'pm' | 'overnight';
export type Startedat = string | null;
export type Startedbyname = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistStatus".
 */
export type ChecklistStatus = 'open' | 'in_progress' | 'complete' | 'missed';
export type Templateid = string;
export type Templatename = string;
export type Total1 = number;
export type Day = string | null;
export type Departmentid4 = string | null;
export type Assignedname1 = string | null;
export type Assigneduserid1 = string | null;
export type Completedbyname1 = string | null;
export type Departmentid5 = string;
export type Departmentname1 = string;
export type Done2 = number;
export type Duedate1 = string;
export type Id9 = string;
export type Ondemand1 = boolean;
export type Outofrangecount1 = number;
export type Templateid1 = string;
export type Templatename1 = string;
export type Total2 = number;
export type Categorykey = string | null;
export type Id10 = string | null;
export type Label1 = string;
export type Maxvalue1 = number | null;
export type Minvalue1 = number | null;
export type Required1 = boolean;
export type Unit1 = string | null;
export type Itemcount = number;
export type Name10 = string;
export type Categories1 = ChecklistLibraryCategoryOut[];
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "DepartmentType".
 */
export type DepartmentType =
  'front_desk' | 'housekeeping' | 'engineering' | 'food_beverage' | 'spa' | 'security' | 'valet' | 'other';
export type Itemcount1 = number;
export type Key1 = string;
export type Name11 = string;
export type Departmentid6 = string;
export type Name12 = string | null;
export type Days = number;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistSchedule".
 */
export type ChecklistSchedule = 'weekly' | 'on_demand' | 'unscheduled';
export type Active7 = boolean;
/**
 * @maxItems 30
 */
export type Categories2 = ChecklistCategoryIn[];
export type Departmentid7 = string;
/**
 * @minItems 1
 * @maxItems 100
 */
export type Items1 = [ChecklistItemIn, ...ChecklistItemIn[]];
/**
 * Drives a filter and a tag only — no behaviour differs (checklist structure spec §1.2).
 */
export type ChecklistKind1 = 'normal' | 'readings';
export type Name13 = string;
export type Weekdays = number | null;
export type Active8 = boolean;
export type Categories3 = ChecklistCategoryOut[];
export type Departmentid8 = string;
export type Departmentname2 = string;
export type Id11 = string;
export type Items2 = ChecklistItemOut[];
export type Name14 = string;
export type Weekdays1 = number | null;
export type Active9 = boolean | null;
export type Categories4 = ChecklistCategoryIn[] | null;
export type Departmentid9 = string | null;
export type Items3 = [ChecklistItemIn, ...ChecklistItemIn[]] | null;
export type Name15 = string | null;
export type Weekdays2 = number | null;
export type Endson = string;
export type Missed = number;
export type Ontimepct = number;
export type Ordinal = number;
export type Passed = number;
export type Startson = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PmCycleStatus".
 */
export type PmCycleStatus = 'open' | 'closed';
export type Total3 = number;
export type Cycles = ComplianceCycleOut[];
export type Id12 = string;
export type Inspectionpassrate = number | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PmTemplateMode".
 */
export type PmTemplateMode = 'sweep' | 'scheduled';
export type Name16 = string;
export type Due = number;
export type Failed = number;
export type Overdue = number;
export type Passed1 = number;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PmUnitKind".
 */
export type PmUnitKind = 'guest_room' | 'common_area' | 'equipment';
export type Templates = ComplianceTemplateOut[];
export type From = string;
export type To = string;
export type Archivedat = string | null;
export type Assigneddepartmentid = string | null;
export type Assigneduserid2 = string | null;
export type Body = string;
export type Createdat1 = string;
export type Id13 = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "DraftPromptStatus".
 */
export type DraftPromptStatus = 'pending' | 'sent' | 'dismissed';
export type Workorderid = string;
export type Workordertitle = string;
export type Draftprompts = DraftPromptOut[];
export type Firstresponseseconds = number | null;
export type Email = string | null;
export type Firstname = string | null;
export type Id14 = string;
export type Lastname = string | null;
export type Loyaltytier = string | null;
export type Notessummary = string | null;
export type Phonee164 = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SmsConsentStatus".
 */
export type SmsConsentStatus = 'unknown' | 'opted_in' | 'opted_out';
export type Vip = boolean;
export type Id15 = string;
export type Lastguestmessageat = string | null;
export type Laststaffmessageat = string | null;
export type Authoruserid = string | null;
export type Body1 = string;
export type Conversationid = string;
export type Deliveredat = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "DeliveryStatus".
 */
export type DeliveryStatus = 'queued' | 'sent' | 'delivered' | 'failed' | 'undelivered';
export type Digitalassetid = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "Direction".
 */
export type Direction = 'inbound' | 'outbound';
export type Id16 = string;
export type Providererrorcode = string | null;
export type Providererrormessage = string | null;
export type Redacted = boolean;
export type Sentat = string | null;
export type Messages = MessageOut[];
export type Authorname = string;
export type Authoruserid1 = string;
export type Body2 = string;
export type Createdat2 = string;
export type Id17 = string;
export type Mentions = string[];
export type Notes = NoteOut[];
export type Resolutioncategoryid = string | null;
export type Sladueat = string | null;
export type Snoozeduntil = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ConversationStatus".
 */
export type ConversationStatus = 'open' | 'snoozed' | 'archived';
export type Adults = number;
export type Arrivaldate = string;
export type Children1 = number;
export type Departuredate = string;
export type Id18 = string;
export type Isreturnguest = boolean;
export type Roomnumber = string | null;
export type Roomtype = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StayStatus".
 */
export type StayStatus = 'reserved' | 'checked_in' | 'checked_out' | 'cancelled' | 'no_show';
export type Staycount = number;
export type Assigneduserid3 = string | null;
export type Completedat1 = string | null;
export type Createdat3 = string;
export type Departmentid10 = string | null;
export type Guestnotifiedat = string | null;
export type Id19 = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "Priority".
 */
export type Priority = 'low' | 'normal' | 'high' | 'urgent';
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderStatus".
 */
export type WorkOrderStatus = 'open' | 'assigned' | 'in_progress' | 'blocked' | 'complete' | 'verified' | 'cancelled';
export type Title = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderType".
 */
export type WorkOrderType = 'maintenance' | 'housekeeping' | 'guest_request' | 'pm' | 'other';
export type Workorders = WorkOrderBrief[];
export type Assigneddepartmentid1 = string | null;
export type Assigneduserid4 = string | null;
export type Clearassignment = boolean;
export type Resolutioncategoryid1 = string | null;
export type Snoozeduntil1 = string | null;
export type Assigneddepartmentid2 = string | null;
export type Assigneduserid5 = string | null;
export type Id20 = string;
export type Lastguestmessageat1 = string | null;
export type Lastmessagepreview = string | null;
export type Laststaffmessageat1 = string | null;
export type Openworkordercount = number;
export type Roomnumber1 = string | null;
export type Sladueat1 = string | null;
export type Snoozeduntil2 = string | null;
export type Unanswered = boolean;
export type Id21 = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "MentionTargetType".
 */
export type MentionTargetType = 'user' | 'department';
/**
 * @maxItems 100
 */
export type Ackaudience = MentionRef[];
export type Body3 = string;
export type Departmentid11 = string | null;
export type Fieldid = string;
export type Value = string | number | null;
/**
 * @maxItems 50
 */
export type Fieldvalues = LogFieldValueIn[];
export type Linkedconversationid = string | null;
export type Linkedworkorderid = string | null;
/**
 * @maxItems 100
 */
export type Mentions1 = MentionRef[];
export type Requiresack = boolean;
export type Templateid2 = string | null;
export type Body4 = string;
export type Kind = 'dm' | 'group';
export type Name17 = string | null;
export type Userid2 = string | null;
export type Userids1 = string[] | null;
export type Departmentid12 = string | null;
export type Email1 = string;
export type Firstname1 = string;
export type Lastname1 = string;
export type Password = string | null;
export type Phone = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "Role".
 */
export type Role = 'agent' | 'dept_staff' | 'supervisor' | 'manager' | 'admin' | 'corporate';
export type Assigneduserid6 = string | null;
export type Departmentid13 = string | null;
export type Description3 = string | null;
export type Dueat = string | null;
export type Locationref = string | null;
export type LocationType = 'room' | 'public_area' | 'equipment' | 'other';
export type Priority1 = 'low' | 'normal' | 'high' | 'urgent';
export type Sourceconversationid = string | null;
export type Sourcemessageid = string | null;
export type Title1 = string;
export type WorkOrderType1 = 'maintenance' | 'housekeeping' | 'guest_request' | 'pm' | 'other';
export type Daysleft = number;
export type Endson1 = string;
export type Id22 = string;
export type Missed1 = number;
export type Ordinal1 = number;
export type Passed2 = number;
export type Startson1 = string;
export type Templateid3 = string;
export type Total4 = number;
export type Count = number;
export type Day1 = string;
export type Closed = number;
export type Departmentid14 = string | null;
export type Departmentname3 = string;
export type Meantimetoresolveseconds = number | null;
export type Active10 = boolean;
export type Escalationminutes = number;
export type Name18 = string;
export type Active11 = boolean;
export type Escalationminutes1 = number;
export type Id23 = string;
export type Name19 = string;
export type Active12 = boolean | null;
export type Escalationminutes2 = number | null;
export type Name20 = string | null;
export type Avatarurl = string | null;
export type Name21 = string | null;
export type Conversationids = string[];
export type Stays = StayOut[];
export type Body5 = string;
export type Id24 = string;
export type Sentat1 = string | null;
export type Messages1 = GuestThreadMessage[];
export type Phone1 = string;
export type Propertyname = string;
export type Housekeeperuserid = string;
/**
 * @minItems 1
 * @maxItems 500
 */
export type Roomids = [string, ...string[]];
export type Completedat2 = string | null;
export type Failcount = number;
export type Housekeepername = string | null;
export type Housekeeperuserid1 = string;
export type Id25 = string;
export type Inspectedat = string | null;
export type Inspectedbyname = string | null;
export type Inspectionnote = string | null;
export type Roomid = string;
export type Sequence = number;
export type Shiftdate = string;
export type Startedat1 = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkAssignmentStatus".
 */
export type HkAssignmentStatus = 'assigned' | 'in_progress' | 'done' | 'passed';
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkServiceType".
 */
export type HkServiceType = 'departure' | 'stayover' | 'touch_up';
export type Assigned = number;
export type Done3 = number;
export type Name22 = string;
export type Userid3 = string;
export type Housekeepers = HkHousekeeperOut[];
export type Code = string;
export type Departuredate1 = string | null;
export type Floor = number | null;
export type Guestname = string | null;
/**
 * `clean` = the housekeeper finished and it awaits inspection; `inspected` = a supervisor
 * passed it (spec §2.1).
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkStatus".
 */
export type HkStatus = 'clean' | 'dirty' | 'in_progress' | 'inspected' | 'out_of_order' | 'out_of_service';
export type Id26 = string;
export type Lastcleanedat = string | null;
export type Lastinspectedat = string | null;
export type Notes1 = string | null;
/**
 * Derived per request from `stay`, never stored (spec §2.1).
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkOccupancy".
 */
export type HkOccupancy = 'vacant' | 'arrival' | 'stayover' | 'departure';
export type Roomtype1 = string | null;
export type Rush = boolean;
export type Statuschangedat = string;
export type Unitid = string;
export type Rooms = HkRoomOut[];
export type Awaitinginspection = number;
export type Dirty = number;
export type Inprogress = number;
export type Inspected = number;
export type Outoforder = number;
export type Comment2 = string | null;
export type Createdat4 = string;
export type Fromvalue = string | null;
export type Id27 = string;
export type Tovalue = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "RoomEventType".
 */
export type RoomEventType =
  | 'status_changed'
  | 'assigned'
  | 'reassigned'
  | 'unassigned'
  | 'started'
  | 'completed'
  | 'inspection_passed'
  | 'inspection_failed'
  | 'marked_dirty'
  | 'rush_set'
  | 'rush_cleared';
export type Username = string | null;
export type Note = string | null;
export type Result = 'pass' | 'fail';
export type Bytesize1 = number;
export type Contenttype1 = string;
export type Createdat5 = string;
export type Id28 = string;
export type Url4 = string;
export type Photos1 = HkPhotoOut[];
export type Note1 = string | null;
/**
 * @minItems 1
 * @maxItems 500
 */
export type Assignmentids = [string, ...string[]];
export type Housekeeperuserid2 = string;
export type Events = HkEventOut[];
export type Photos2 = HkPhotoOut[];
export type Note2 = string | null;
export type Status = 'out_of_order' | 'out_of_service' | 'dirty';
export type Count1 = number;
export type Hour = number;
export type Note3 = string | null;
export type Result1 = 'pass' | 'fail';
export type Sort = 'days_since_last_pm' | 'completed_at';
export type Status1 = 'available' | 'inspected';
export type Completedat3 = string | null;
export type Completedbyname2 = string | null;
export type Dayssincelastpm = number | null;
export type Inspectedat1 = string | null;
export type Inspectedbyname1 = string | null;
export type Runid = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PmRunStatus".
 */
export type PmRunStatus = 'pending' | 'in_progress' | 'completed' | 'passed' | 'failed' | 'missed';
export type Templatename2 = string;
export type Unitcode = string;
export type Unitid1 = string;
export type Unitname = string;
export type Dept = string | null;
export type Filter = string;
export type Limit = number;
export type Offset = number;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LocationType".
 */
export type LocationType1 = 'room' | 'public_area' | 'equipment' | 'other';
export type Acknowledgedat = string;
export type Name23 = string;
export type Userid4 = string;
export type Ackexpectedcount = number;
export type Ackedbyme = boolean;
export type Acks = LogAckOut[];
export type Authoravatarurl = string | null;
export type Authorname1 = string;
export type Authoruserid2 = string;
export type Body6 = string;
export type Canack = boolean;
export type Createdat6 = string;
export type Departmentid15 = string | null;
export type Departmentname4 = string | null;
export type Fieldid1 = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogFieldType".
 */
export type LogFieldType = 'short_text' | 'long_text' | 'integer' | 'decimal' | 'percent';
export type Label2 = string;
export type Numbervalue2 = number | null;
export type Textvalue2 = string | null;
export type Fieldvalues1 = LogFieldValueOut[];
export type Id29 = string;
export type Linkedconversationid1 = string | null;
export type Linkedworkorderid1 = string | null;
export type Displayname = string;
export type Id30 = string;
export type Mentions2 = LogMentionOut[];
export type Notes2 = string | null;
export type Name24 = string;
export type Userid5 = string;
export type Outstanding = LogPersonOut[];
export type Photourl = string | null;
export type Pinned = boolean;
export type Pinnedat = string | null;
export type Pinnedbyuserid = string | null;
export type Requiresack1 = boolean;
export type Id31 = string;
export type Name25 = string;
export type Entries = LogEntryOut[];
export type Nextcursor = string | null;
export type Pinned1 = LogEntryOut[];
export type Cursor = string | null;
export type Departmentid16 = string | null;
export type From1 = string | null;
export type Mentioningme = boolean;
export type To1 = string | null;
export type Displayname1 = string;
export type Id32 = string;
export type Subtitle = string | null;
export type Id33 = string | null;
export type Label3 = string;
export type Required2 = boolean;
export type Active13 = boolean;
export type Id34 = string;
export type Label4 = string;
export type Position3 = number;
export type Required3 = boolean;
export type Active14 = boolean;
/**
 * @maxItems 100
 */
export type Audience = MentionRef[];
/**
 * @minItems 1
 * @maxItems 50
 */
export type Fields = [LogTemplateFieldIn, ...LogTemplateFieldIn[]];
export type Name26 = string;
export type Active15 = boolean;
export type Audience1 = MentionRef[];
export type Fields1 = LogTemplateFieldOut[];
export type Id35 = string;
export type Name27 = string;
export type Position4 = number;
export type Usedcount = number;
export type Active16 = boolean | null;
export type Audience2 = MentionRef[] | null;
export type Fields2 = [LogTemplateFieldIn, ...LogTemplateFieldIn[]] | null;
export type Name28 = string | null;
export type Email2 = string;
export type Password1 = string;
export type Departmentid17 = string | null;
export type Propertycode = string;
export type Propertyid = string;
export type Propertyname1 = string;
export type Body7 = string | null;
export type Createdat7 = string;
export type Entityid = string | null;
export type Entitytype = string | null;
export type Id36 = string;
export type Readat = string | null;
export type Title2 = string;
export type Type = string;
export type Conversations = number;
export type Count2 = number;
export type Label5 = string;
export type Share = number;
export type Firstresponsedistribution = ResponseBucket[];
export type Firstresponsep50Seconds1 = number | null;
export type Firstresponsep90Seconds1 = number | null;
export type Inboundbyday = DayBucket[];
export type Inboundbyhour = HourBucket[];
export type Inboundmessages = number;
export type Meantimetoresolveseconds1 = number | null;
export type Outboundmessages = number;
export type Since = string;
export type Slabreachrate = number;
export type Slabreaches1 = number;
export type Until = string;
export type Workordersbydepartment = DepartmentBucket[];
export type Workordersclosed = number;
export type Workorderscreated1 = number;
export type Workordersfromconversations = number;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PmCadence".
 */
export type PmCadence = 'monthly' | 'quarterly' | 'semiannual' | 'annual';
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PmUnitSource".
 */
export type PmUnitSource = 'manual' | 'csv' | 'pms';
export type Theme = ('dark' | 'light' | 'system') | null;
export type Body8 = string;
export type Conversationid1 = string | null;
export type Address = string | null;
export type Autoresolvehours = number;
export type Brand = string | null;
export type Code1 = string;
export type Currency = string;
export type Helptext = string | null;
export type Id37 = string;
export type Logourl = string | null;
export type Name29 = string;
export type Phone2 = string | null;
export type Primarycolor = string | null;
export type Slaminutes = number;
export type Smsnumber = string | null;
export type Timezone = string;
export type Address1 = string | null;
export type Autoresolvehours1 = number | null;
export type Brand1 = string | null;
export type Currency1 = string | null;
export type Helptext1 = string | null;
export type Logourl1 = string | null;
export type Name30 = string | null;
export type Phone3 = string | null;
export type Primarycolor1 = string | null;
export type Slaminutes1 = number | null;
export type Smsnumber1 = string | null;
export type Timezone1 = string | null;
export type Active17 = boolean;
export type Body9 = string;
export type Category3 = string | null;
export type Departmentid18 = string | null;
export type Locale = string;
export type Shortcut = string;
export type Title3 = string;
export type Active18 = boolean;
export type Body10 = string;
export type Category4 = string | null;
export type Departmentid19 = string | null;
export type Id38 = string;
export type Locale1 = string;
export type Shortcut1 = string;
export type Title4 = string;
export type Usagecount = number;
export type Active19 = boolean | null;
export type Body11 = string | null;
export type Category5 = string | null;
export type Departmentid20 = string | null;
export type Locale2 = string | null;
export type Shortcut2 = string | null;
export type Title5 = string | null;
export type Conversationid2 = string;
export type Body12 = string;
export type Characters = number;
export type Segments = number;
export type Answers1 = RunAnswerOut[];
export type Completedat4 = string | null;
export type Cycleid = string | null;
export type Dueat1 = string | null;
export type Id39 = string;
export type Inspectedat2 = string | null;
export type Inspectedbyname2 = string | null;
export type Inspectedbyuserid = string | null;
export type Inspectionnote1 = string | null;
export type Active20 = boolean;
export type Id40 = string;
export type Label6 = string;
export type Maxvalue2 = number | null;
export type Minvalue2 = number | null;
export type Position5 = number;
export type Required4 = boolean;
export type Unit2 = string | null;
export type Items4 = TemplateItemOut[];
export type Missingrequired1 = string[];
export type Photos3 = RunPhotoOut[];
export type Startedat2 = string | null;
export type Startedbyname1 = string | null;
export type Startedbyuserid = string | null;
export type Templateid4 = string;
export type Templatename3 = string;
export type Unitcode1 = string;
export type Unitid2 = string;
export type Unitname1 = string;
export type Workorderid1 = string | null;
export type Body13 = string;
export type Digitalassetid1 = string | null;
export type Draftpromptid = string | null;
export type Body14 = string | null;
export type Memberships = MembershipOut[];
export type Avatarurl1 = string | null;
export type Email3 = string;
export type Firstname2 = string;
export type Id41 = string;
export type Lastname2 = string;
export type Locale3 = string;
export type At = string;
export type Propertyid1 = string;
export type Type1 = string;
export type Guestid = string;
export type Inhouse = boolean;
export type Name31 = string;
export type Phone4 = string;
export type Propertyid2 = string;
export type Propertyname2 = string;
export type Propertysmsnumber = string | null;
export type Roomnumber2 = string | null;
export type Stayid = string | null;
export type Willfail = boolean;
export type Avatarurl2 = string | null;
export type Createdat8 = string;
export type Displayname2 = string;
export type Id42 = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StaffConversationKind".
 */
export type StaffConversationKind = 'dm' | 'group' | 'all';
export type Lastmessageat = string | null;
export type Lastmessagepreview1 = string | null;
export type Authorname2 = string;
export type Authoruserid3 = string;
export type Body15 = string | null;
export type Conversationid3 = string;
export type Createdat9 = string;
export type Id43 = string;
export type Photourl1 = string | null;
export type Messages2 = StaffMessageOut[];
export type Name32 = string | null;
export type Otheruserid = string | null;
export type Avatarurl3 = string | null;
export type Departmentid21 = string | null;
export type Firstname3 = string;
export type Lastname3 = string;
export type Userid6 = string;
export type Participants = StaffParticipantOut[];
export type Unread = boolean;
export type Updatedat = string;
export type Avatarurl4 = string | null;
export type Createdat10 = string;
export type Displayname3 = string;
export type Id44 = string;
export type Lastmessageat1 = string | null;
export type Lastmessagepreview2 = string | null;
export type Name33 = string | null;
export type Otheruserid1 = string | null;
export type Participants1 = StaffParticipantOut[];
export type Unread1 = boolean;
export type Updatedat1 = string;
export type Avatarurl5 = string | null;
export type Departmentid22 = string | null;
export type Departmentname5 = string | null;
export type Firstname4 = string;
export type Lastname4 = string;
export type Userid7 = string;
export type Departmentid23 = string | null;
export type Avatarurl6 = string | null;
export type Departmentid24 = string | null;
export type Email4 = string;
export type Firstname5 = string;
export type Id45 = string;
export type Lastname5 = string;
export type Status2 = string;
export type Templateid5 = string;
export type Unitid3 = string;
export type Completed = number;
export type Remaining = number;
export type Total5 = number;
export type Daysleft1 = number;
export type Endson2 = string;
export type Id46 = string;
export type Ordinal2 = number;
export type Startson2 = string;
export type Id47 = string;
export type Name34 = string;
export type Code2 = string;
export type Id48 = string;
export type Startedbyname2 = string | null;
export type Startedbyuserid1 = string | null;
export type Floor1 = number | null;
export type Id49 = string;
export type Lastpassedat = string | null;
export type Lastpassedbyname = string | null;
export type Name35 = string;
export type Passedthiscycle = boolean;
export type Roomtype2 = string | null;
export type Units = SweepUnitOut[];
export type Q = string | null;
export type Sort1 = 'code' | 'floor' | 'days_since_last_pm';
export type Status3 = ('remaining' | 'completed') | null;
export type Active21 = boolean;
export type Departmentid25 = string | null;
export type Id50 = string | null;
export type Label7 = string;
export type Maxvalue3 = number | null;
export type Minvalue3 = number | null;
export type Required5 = boolean;
export type Unit3 = string | null;
/**
 * @maxItems 100
 */
export type Items5 = TemplateItemIn[];
export type Name36 = string;
export type Rrule = string | null;
export type Rruledtstart = string | null;
/**
 * @maxItems 500
 */
export type Unitids = string[];
export type Active22 = boolean;
export type Createdat11 = string;
export type Departmentid26 = string | null;
export type Hasruns = boolean;
export type Id51 = string;
export type Items6 = TemplateItemOut[];
export type Lastfiredat = string | null;
export type Name37 = string;
export type Rrule1 = string | null;
export type Rruledtstart1 = string | null;
export type Unitids1 = string[];
export type Active23 = boolean | null;
export type Departmentid27 = string | null;
export type Items7 = TemplateItemIn[] | null;
export type Name38 = string | null;
export type Rrule2 = string | null;
export type Rruledtstart2 = string | null;
export type Unitids2 = string[] | null;
export type Field = string;
export type Line = number;
export type Message = string;
export type Created = number;
export type Errors = UnitImportError[];
export type Updated = number;
export type Code3 = string;
export type Externalid = string | null;
export type Floor2 = number | null;
export type Name39 = string;
export type Notes3 = string | null;
export type Roomtype3 = string | null;
export type Active24 = boolean | null;
export type Q1 = string | null;
export type Active25 = boolean;
export type Code4 = string;
export type Createdat12 = string;
export type Externalid1 = string | null;
export type Floor3 = number | null;
export type Id52 = string;
export type Name40 = string;
export type Notes4 = string | null;
export type Roomtype4 = string | null;
export type Active26 = boolean | null;
export type Code5 = string | null;
export type Externalid2 = string | null;
export type Floor4 = number | null;
export type Name41 = string | null;
export type Notes5 = string | null;
export type Roomtype5 = string | null;
export type Count3 = number;
export type Acknowledgedat1 = string | null;
export type Assigneduserid7 = string | null;
export type Completedat5 = string | null;
export type Createdat13 = string;
export type Departmentid28 = string | null;
export type Description4 = string | null;
export type Dueat2 = string | null;
export type Comment3 = string | null;
export type Createdat14 = string;
export type Fromvalue1 = string | null;
export type Id53 = string;
export type Tovalue1 = string | null;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderEventType".
 */
export type WorkOrderEventType =
  'created' | 'status_changed' | 'assigned' | 'commented' | 'priority_changed' | 'photo_attached';
export type Userid8 = string | null;
export type Username1 = string | null;
export type Events1 = WorkOrderEventOut[];
export type Guestname1 = string | null;
export type Guestnotifiedat1 = string | null;
export type Id54 = string;
export type Locationref1 = string | null;
export type Bytesize2 = number;
export type Contenttype2 = string;
export type Createdat15 = string;
export type Id55 = string;
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderPhotoKind".
 */
export type WorkOrderPhotoKind = 'before' | 'after';
export type Uploadedbyname = string | null;
export type Uploadedbyuserid1 = string | null;
export type Url5 = string;
export type Workorderid2 = string;
export type Photos4 = WorkOrderPhotoOut[];
export type Pmrunid = string | null;
export type Reportedbyuserid = string | null;
export type Roomnumber3 = string | null;
export type Sourceconversationid1 = string | null;
export type Sourcemessageid1 = string | null;
export type Startedat3 = string | null;
export type Title6 = string;
export type Updatedat2 = string;
export type Verifiedat = string | null;
export type Assignee = string | null;
export type Dept1 = string | null;
export type Includeclosed = boolean;
export type Mine = boolean;
export type Status4 = string | null;
export type Acknowledgedat2 = string | null;
export type Assigneduserid8 = string | null;
export type Completedat6 = string | null;
export type Createdat16 = string;
export type Departmentid29 = string | null;
export type Description5 = string | null;
export type Dueat3 = string | null;
export type Guestnotifiedat2 = string | null;
export type Id56 = string;
export type Locationref2 = string | null;
export type Reportedbyuserid1 = string | null;
export type Sourceconversationid2 = string | null;
export type Sourcemessageid2 = string | null;
export type Startedat4 = string | null;
export type Title7 = string;
export type Updatedat3 = string;
export type Verifiedat1 = string | null;
export type Assigneduserid9 = string | null;
export type Clearassignee = boolean;
export type Comment4 = string | null;
export type Departmentid30 = string | null;
export type Departmentid31 = string | null;
export type Description6 = string;
export type Guestname2 = string | null;
export type Locationref3 = string | null;
export type Sourceconversationid3 = string;
export type Sourcemessageid3 = string | null;
export type Title8 = string;

export interface RelayAPI {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "AddParticipantsRequest".
 */
export interface AddParticipantsRequest {
  userIds: Userids;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "AgentStats".
 */
export interface AgentStats {
  conversationsHandled: Conversationshandled;
  firstResponseP50Seconds?: Firstresponsep50Seconds;
  firstResponseP90Seconds?: Firstresponsep90Seconds;
  messagesSent: Messagessent;
  name: Name;
  quickReplyShare?: Quickreplyshare;
  slaBreaches: Slabreaches;
  userId: Userid;
  workOrdersCreated: Workorderscreated;
}
/**
 * Exactly one of these, matching the item's type (spec §4.2).
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "AnswerPatch".
 */
export interface AnswerPatch {
  boolValue?: Boolvalue;
  numberValue?: Numbervalue;
  textValue?: Textvalue;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "AssetIn".
 */
export interface AssetIn {
  active?: Active;
  category?: Category;
  departmentId?: Departmentid;
  description?: Description;
  name: Name1;
  thumbnailUrl?: Thumbnailurl;
  type?: AssetType;
  url: Url;
  validFrom?: Validfrom;
  validUntil?: Validuntil;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "AssetOut".
 */
export interface AssetOut {
  active: Active1;
  category?: Category1;
  departmentId?: Departmentid1;
  description?: Description1;
  id: Id;
  name: Name2;
  sendCount: Sendcount;
  shortCode: Shortcode;
  thumbnailUrl?: Thumbnailurl1;
  type: AssetType1;
  url: Url1;
  validFrom?: Validfrom1;
  validUntil?: Validuntil1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "AssetPatch".
 */
export interface AssetPatch {
  active?: Active2;
  category?: Category2;
  departmentId?: Departmentid2;
  description?: Description2;
  name?: Name3;
  thumbnailUrl?: Thumbnailurl2;
  type?: AssetType1 | null;
  url?: Url2;
  validFrom?: Validfrom2;
  validUntil?: Validuntil2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "CategoryIn".
 */
export interface CategoryIn {
  active?: Active3;
  name: Name4;
  parentId?: Parentid;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "CategoryOut".
 */
export interface CategoryOut {
  active: Active4;
  children?: Children;
  id: Id1;
  name: Name5;
  parentId?: Parentid1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "CategoryPatch".
 */
export interface CategoryPatch {
  active?: Active5;
  name?: Name6;
  parentId?: Parentid2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistAssignRequest".
 */
export interface ChecklistAssignRequest {
  userId?: Userid1;
}
/**
 * `key` is the client's handle for this category within one request; `id` names a saved
 * category to update in place. A saved category missing from the list is soft-deleted.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistCategoryIn".
 */
export interface ChecklistCategoryIn {
  id?: Id2;
  key: Key;
  name: Name7;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistCategoryOut".
 */
export interface ChecklistCategoryOut {
  id: Id3;
  name: Name8;
  position: Position;
}
/**
 * A category heading on the checklist page: `done / total` over its items.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistCategoryProgressOut".
 */
export interface ChecklistCategoryProgressOut {
  done: Done;
  id: Id4;
  name: Name9;
  position: Position1;
  total: Total;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistCommentPatch".
 */
export interface ChecklistCommentPatch {
  comment?: Comment;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistInstanceOut".
 */
export interface ChecklistInstanceOut {
  answers: Answers;
  assignedName?: Assignedname;
  assignedUserId?: Assigneduserid;
  categories: Categories;
  comment?: Comment1;
  completedAt?: Completedat;
  completedByName?: Completedbyname;
  departmentId: Departmentid3;
  departmentName: Departmentname;
  done: Done1;
  dueDate: Duedate;
  id: Id6;
  items: Items;
  kind: ChecklistKind;
  missingRequired: Missingrequired;
  onDemand: Ondemand;
  outOfRangeCount: Outofrangecount;
  photos: Photos;
  shift: Shift;
  startedAt?: Startedat;
  startedByName?: Startedbyname;
  status: ChecklistStatus;
  templateId: Templateid;
  templateName: Templatename;
  total: Total1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "RunAnswerOut".
 */
export interface RunAnswerOut {
  answeredAt?: Answeredat;
  boolValue?: Boolvalue1;
  id: Id5;
  itemId: Itemid;
  numberValue?: Numbervalue1;
  outOfRange: Outofrange;
  textValue?: Textvalue1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistItemOut".
 */
export interface ChecklistItemOut {
  active: Active6;
  categoryId?: Categoryid;
  id: Id7;
  itemType: PmItemType;
  label: Label;
  maxValue?: Maxvalue;
  minValue?: Minvalue;
  position: Position2;
  required: Required;
  unit?: Unit;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "RunPhotoOut".
 */
export interface RunPhotoOut {
  byteSize: Bytesize;
  contentType: Contenttype;
  createdAt: Createdat;
  id: Id8;
  itemId?: Itemid1;
  uploadedByUserId?: Uploadedbyuserid;
  url: Url3;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistInstanceQuery".
 */
export interface ChecklistInstanceQuery {
  day?: Day;
  departmentId?: Departmentid4;
  status?: ChecklistStatus | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistInstanceRowOut".
 */
export interface ChecklistInstanceRowOut {
  assignedName?: Assignedname1;
  assignedUserId?: Assigneduserid1;
  completedByName?: Completedbyname1;
  departmentId: Departmentid5;
  departmentName: Departmentname1;
  done: Done2;
  dueDate: Duedate1;
  id: Id9;
  kind: ChecklistKind;
  onDemand: Ondemand1;
  outOfRangeCount: Outofrangecount1;
  shift: Shift;
  status: ChecklistStatus;
  templateId: Templateid1;
  templateName: Templatename1;
  total: Total2;
}
/**
 * PM's item plus the category it sits under, named by a `key` from the same request's
 * `categories` (checklist structure spec §3.2). PM's own TemplateItemIn is unchanged.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistItemIn".
 */
export interface ChecklistItemIn {
  categoryKey?: Categorykey;
  id?: Id10;
  itemType: PmItemType;
  label: Label1;
  maxValue?: Maxvalue1;
  minValue?: Minvalue1;
  required?: Required1;
  unit?: Unit1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistLibraryCategoryOut".
 */
export interface ChecklistLibraryCategoryOut {
  itemCount: Itemcount;
  name: Name10;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistLibraryEntryOut".
 */
export interface ChecklistLibraryEntryOut {
  categories: Categories1;
  departmentType: DepartmentType;
  itemCount: Itemcount1;
  key: Key1;
  kind: ChecklistKind;
  name: Name11;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistLibraryImport".
 */
export interface ChecklistLibraryImport {
  departmentId: Departmentid6;
  name?: Name12;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistMissedQuery".
 */
export interface ChecklistMissedQuery {
  days?: Days;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistTemplateIn".
 */
export interface ChecklistTemplateIn {
  active?: Active7;
  categories?: Categories2;
  departmentId: Departmentid7;
  items: Items1;
  kind?: ChecklistKind1;
  name: Name13;
  schedule: ChecklistSchedule;
  shift?: Shift | null;
  weekdays?: Weekdays;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistTemplateOut".
 */
export interface ChecklistTemplateOut {
  active: Active8;
  categories: Categories3;
  departmentId: Departmentid8;
  departmentName: Departmentname2;
  id: Id11;
  items: Items2;
  kind: ChecklistKind;
  name: Name14;
  schedule: ChecklistSchedule;
  shift?: Shift | null;
  weekdays?: Weekdays1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ChecklistTemplatePatch".
 */
export interface ChecklistTemplatePatch {
  active?: Active9;
  categories?: Categories4;
  departmentId?: Departmentid9;
  items?: Items3;
  kind?: ChecklistKind | null;
  name?: Name15;
  schedule?: ChecklistSchedule | null;
  shift?: Shift | null;
  weekdays?: Weekdays2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ComplianceCycleOut".
 */
export interface ComplianceCycleOut {
  endsOn: Endson;
  missed: Missed;
  onTimePct: Ontimepct;
  ordinal: Ordinal;
  passed: Passed;
  startsOn: Startson;
  status: PmCycleStatus;
  total: Total3;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ComplianceOut".
 */
export interface ComplianceOut {
  templates?: Templates;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ComplianceTemplateOut".
 */
export interface ComplianceTemplateOut {
  cycles?: Cycles;
  id: Id12;
  inspectionPassRate?: Inspectionpassrate;
  mode: PmTemplateMode;
  name: Name16;
  runs?: ComplianceRunsOut | null;
  unitKind?: PmUnitKind | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ComplianceRunsOut".
 */
export interface ComplianceRunsOut {
  due: Due;
  failed: Failed;
  overdue: Overdue;
  passed: Passed1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ComplianceQuery".
 */
export interface ComplianceQuery {
  from: From;
  to: To;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ConversationDetail".
 */
export interface ConversationDetail {
  archivedAt?: Archivedat;
  assignedDepartmentId?: Assigneddepartmentid;
  assignedUserId?: Assigneduserid2;
  channelPrimary: Channel;
  draftPrompts: Draftprompts;
  firstResponseSeconds?: Firstresponseseconds;
  guest: GuestOut;
  id: Id15;
  lastGuestMessageAt?: Lastguestmessageat;
  lastStaffMessageAt?: Laststaffmessageat;
  messages: Messages;
  notes: Notes;
  resolutionCategoryId?: Resolutioncategoryid;
  slaDueAt?: Sladueat;
  snoozedUntil?: Snoozeduntil;
  status: ConversationStatus;
  stay?: StayOut | null;
  workOrders: Workorders;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "DraftPromptOut".
 */
export interface DraftPromptOut {
  body: Body;
  createdAt: Createdat1;
  id: Id13;
  status: DraftPromptStatus;
  workOrderId: Workorderid;
  workOrderTitle: Workordertitle;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "GuestOut".
 */
export interface GuestOut {
  email?: Email;
  firstName?: Firstname;
  id: Id14;
  lastName?: Lastname;
  loyaltyTier?: Loyaltytier;
  notesSummary?: Notessummary;
  phoneE164: Phonee164;
  smsConsentStatus: SmsConsentStatus;
  vip: Vip;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "MessageOut".
 */
export interface MessageOut {
  authorType: AuthorType;
  authorUserId?: Authoruserid;
  body: Body1;
  channel: Channel;
  conversationId: Conversationid;
  deliveredAt?: Deliveredat;
  deliveryStatus: DeliveryStatus;
  digitalAssetId?: Digitalassetid;
  direction: Direction;
  id: Id16;
  providerErrorCode?: Providererrorcode;
  providerErrorMessage?: Providererrormessage;
  redacted: Redacted;
  sentAt?: Sentat;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "NoteOut".
 */
export interface NoteOut {
  authorName: Authorname;
  authorUserId: Authoruserid1;
  body: Body2;
  createdAt: Createdat2;
  id: Id17;
  mentions: Mentions;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StayOut".
 */
export interface StayOut {
  adults: Adults;
  arrivalDate: Arrivaldate;
  children: Children1;
  departureDate: Departuredate;
  id: Id18;
  isReturnGuest: Isreturnguest;
  roomNumber?: Roomnumber;
  roomType?: Roomtype;
  status: StayStatus;
  stayCount: Staycount;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderBrief".
 */
export interface WorkOrderBrief {
  assignedUserId?: Assigneduserid3;
  completedAt?: Completedat1;
  createdAt: Createdat3;
  departmentId?: Departmentid10;
  guestNotifiedAt?: Guestnotifiedat;
  id: Id19;
  priority: Priority;
  status: WorkOrderStatus;
  title: Title;
  type: WorkOrderType;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ConversationPatch".
 */
export interface ConversationPatch {
  assignedDepartmentId?: Assigneddepartmentid1;
  assignedUserId?: Assigneduserid4;
  clearAssignment?: Clearassignment;
  resolutionCategoryId?: Resolutioncategoryid1;
  snoozedUntil?: Snoozeduntil1;
  status?: ConversationStatus | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ConversationSummary".
 */
export interface ConversationSummary {
  assignedDepartmentId?: Assigneddepartmentid2;
  assignedUserId?: Assigneduserid5;
  channelPrimary: Channel;
  guest: GuestOut;
  id: Id20;
  lastGuestMessageAt?: Lastguestmessageat1;
  lastMessagePreview?: Lastmessagepreview;
  lastStaffMessageAt?: Laststaffmessageat1;
  openWorkOrderCount: Openworkordercount;
  roomNumber?: Roomnumber1;
  slaDueAt?: Sladueat1;
  snoozedUntil?: Snoozeduntil2;
  status: ConversationStatus;
  unanswered: Unanswered;
}
/**
 * The non-file half of the body; a `photo` file part may arrive alongside it, exactly
 * like SendStaffMessageRequest. With `template_id`, `body` is the author's optional notes and
 * the domain generates the stored body (log templates spec §2.2).
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "CreateLogEntryRequest".
 */
export interface CreateLogEntryRequest {
  ackAudience?: Ackaudience;
  body?: Body3;
  departmentId?: Departmentid11;
  fieldValues?: Fieldvalues;
  linkedConversationId?: Linkedconversationid;
  linkedWorkOrderId?: Linkedworkorderid;
  mentions?: Mentions1;
  requiresAck?: Requiresack;
  templateId?: Templateid2;
}
/**
 * One @mention or one member of an acknowledgement audience.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "MentionRef".
 */
export interface MentionRef {
  id: Id21;
  type: MentionTargetType;
}
/**
 * One answer on a templated post. A JSON number or a numeric string (the multipart path
 * sends strings); the domain validates it against the field's type (log templates spec §2.3).
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogFieldValueIn".
 */
export interface LogFieldValueIn {
  fieldId: Fieldid;
  value?: Value;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "CreateNoteRequest".
 */
export interface CreateNoteRequest {
  body: Body4;
}
/**
 * POST /staff-conversations. `kind` picks which of the other fields apply; validated
 * together in app.domain.staff_messages.create_conversation rather than as two separate
 * Pydantic models, so the route stays a single endpoint (spec §3).
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "CreateStaffConversationRequest".
 */
export interface CreateStaffConversationRequest {
  kind: Kind;
  name?: Name17;
  userId?: Userid2;
  userIds?: Userids1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "CreateStaffRequest".
 */
export interface CreateStaffRequest {
  departmentId?: Departmentid12;
  email: Email1;
  firstName: Firstname1;
  lastName: Lastname1;
  password?: Password;
  phone?: Phone;
  role: Role;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "CreateWorkOrder".
 */
export interface CreateWorkOrder {
  assignedUserId?: Assigneduserid6;
  departmentId?: Departmentid13;
  description?: Description3;
  dueAt?: Dueat;
  locationRef?: Locationref;
  locationType?: LocationType;
  priority?: Priority1;
  sourceConversationId?: Sourceconversationid;
  sourceMessageId?: Sourcemessageid;
  title: Title1;
  type?: WorkOrderType1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "CycleOut".
 */
export interface CycleOut {
  daysLeft: Daysleft;
  endsOn: Endson1;
  id: Id22;
  missed: Missed1;
  ordinal: Ordinal1;
  passed: Passed2;
  startsOn: Startson1;
  status: PmCycleStatus;
  templateId: Templateid3;
  total: Total4;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "DayBucket".
 */
export interface DayBucket {
  count: Count;
  day: Day1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "DepartmentBucket".
 */
export interface DepartmentBucket {
  closed: Closed;
  departmentId?: Departmentid14;
  departmentName: Departmentname3;
  meanTimeToResolveSeconds?: Meantimetoresolveseconds;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "DepartmentIn".
 */
export interface DepartmentIn {
  active?: Active10;
  escalationMinutes?: Escalationminutes;
  name: Name18;
  type: DepartmentType;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "DepartmentOut".
 */
export interface DepartmentOut {
  active: Active11;
  escalationMinutes: Escalationminutes1;
  id: Id23;
  name: Name19;
  type: DepartmentType;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "DepartmentPatch".
 */
export interface DepartmentPatch {
  active?: Active12;
  escalationMinutes?: Escalationminutes2;
  name?: Name20;
  type?: DepartmentType | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "GroupPatch".
 */
export interface GroupPatch {
  avatarUrl?: Avatarurl;
  name?: Name21;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "GuestDetail".
 */
export interface GuestDetail {
  conversationIds: Conversationids;
  guest: GuestOut;
  stays: Stays;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "GuestThread".
 */
export interface GuestThread {
  messages: Messages1;
  phone: Phone1;
  propertyName: Propertyname;
}
/**
 * What a guest could ever see. Deliberately has no field that could carry an internal note.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "GuestThreadMessage".
 */
export interface GuestThreadMessage {
  body: Body5;
  deliveryStatus: DeliveryStatus;
  direction: Direction;
  id: Id24;
  sentAt?: Sentat1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkAssignRequest".
 */
export interface HkAssignRequest {
  housekeeperUserId: Housekeeperuserid;
  roomIds: Roomids;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkAssignmentOut".
 */
export interface HkAssignmentOut {
  completedAt?: Completedat2;
  failCount: Failcount;
  housekeeperName?: Housekeepername;
  housekeeperUserId: Housekeeperuserid1;
  id: Id25;
  inspectedAt?: Inspectedat;
  inspectedByName?: Inspectedbyname;
  inspectionNote?: Inspectionnote;
  roomId: Roomid;
  sequence: Sequence;
  shiftDate: Shiftdate;
  startedAt?: Startedat1;
  status: HkAssignmentStatus;
  type: HkServiceType;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkBoardOut".
 */
export interface HkBoardOut {
  housekeepers: Housekeepers;
  rooms: Rooms;
  summary: HkSummaryOut;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkHousekeeperOut".
 */
export interface HkHousekeeperOut {
  assigned: Assigned;
  done: Done3;
  name: Name22;
  userId: Userid3;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkRoomOut".
 */
export interface HkRoomOut {
  assignment?: HkAssignmentOut | null;
  code: Code;
  departureDate?: Departuredate1;
  floor?: Floor;
  guestName?: Guestname;
  hkStatus: HkStatus;
  id: Id26;
  lastCleanedAt?: Lastcleanedat;
  lastInspectedAt?: Lastinspectedat;
  notes?: Notes1;
  occupancy: HkOccupancy;
  roomType?: Roomtype1;
  rush: Rush;
  serviceType?: HkServiceType | null;
  statusChangedAt: Statuschangedat;
  unitId: Unitid;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkSummaryOut".
 */
export interface HkSummaryOut {
  awaitingInspection: Awaitinginspection;
  dirty: Dirty;
  inProgress: Inprogress;
  inspected: Inspected;
  outOfOrder: Outoforder;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkEventOut".
 */
export interface HkEventOut {
  comment?: Comment2;
  createdAt: Createdat4;
  fromValue?: Fromvalue;
  id: Id27;
  toValue?: Tovalue;
  type: RoomEventType;
  userName?: Username;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkInspectRequest".
 */
export interface HkInspectRequest {
  note?: Note;
  result: Result;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkInspectionRowOut".
 */
export interface HkInspectionRowOut {
  photos: Photos1;
  room: HkRoomOut;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkPhotoOut".
 */
export interface HkPhotoOut {
  byteSize: Bytesize1;
  contentType: Contenttype1;
  createdAt: Createdat5;
  id: Id28;
  url: Url4;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkMarkDirtyRequest".
 */
export interface HkMarkDirtyRequest {
  note?: Note1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkReorderRequest".
 */
export interface HkReorderRequest {
  assignmentIds: Assignmentids;
  housekeeperUserId: Housekeeperuserid2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkRoomDetailOut".
 */
export interface HkRoomDetailOut {
  events: Events;
  photos: Photos2;
  room: HkRoomOut;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HkStatusRequest".
 */
export interface HkStatusRequest {
  note?: Note2;
  status: Status;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "HourBucket".
 */
export interface HourBucket {
  count: Count1;
  hour: Hour;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "InspectRequest".
 */
export interface InspectRequest {
  note?: Note3;
  result: Result1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "InspectionQuery".
 */
export interface InspectionQuery {
  kind?: PmUnitKind | null;
  sort?: Sort;
  status?: Status1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "InspectionRowOut".
 */
export interface InspectionRowOut {
  completedAt?: Completedat3;
  completedByName?: Completedbyname2;
  daysSinceLastPm?: Dayssincelastpm;
  inspectedAt?: Inspectedat1;
  inspectedByName?: Inspectedbyname1;
  runId: Runid;
  status: PmRunStatus;
  templateName: Templatename2;
  unitCode: Unitcode;
  unitId: Unitid1;
  unitKind: PmUnitKind;
  unitName: Unitname;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ListQuery".
 */
export interface ListQuery {
  dept?: Dept;
  filter?: Filter;
  limit?: Limit;
  offset?: Offset;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogAckOut".
 */
export interface LogAckOut {
  acknowledgedAt: Acknowledgedat;
  name: Name23;
  userId: Userid4;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogEntryOut".
 */
export interface LogEntryOut {
  ackExpectedCount: Ackexpectedcount;
  ackedByMe: Ackedbyme;
  acks?: Acks;
  authorAvatarUrl?: Authoravatarurl;
  authorName: Authorname1;
  authorUserId: Authoruserid2;
  body: Body6;
  canAck: Canack;
  createdAt: Createdat6;
  departmentId?: Departmentid15;
  departmentName?: Departmentname4;
  fieldValues?: Fieldvalues1;
  id: Id29;
  linkedConversationId?: Linkedconversationid1;
  linkedWorkOrderId?: Linkedworkorderid1;
  mentions?: Mentions2;
  notes?: Notes2;
  outstanding?: Outstanding;
  photoUrl?: Photourl;
  pinned: Pinned;
  pinnedAt?: Pinnedat;
  pinnedByUserId?: Pinnedbyuserid;
  requiresAck: Requiresack1;
  shift: Shift;
  template?: LogTemplateRef | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogFieldValueOut".
 */
export interface LogFieldValueOut {
  fieldId: Fieldid1;
  fieldType: LogFieldType;
  label: Label2;
  numberValue?: Numbervalue2;
  textValue?: Textvalue2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogMentionOut".
 */
export interface LogMentionOut {
  displayName: Displayname;
  id: Id30;
  type: MentionTargetType;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogPersonOut".
 */
export interface LogPersonOut {
  name: Name24;
  userId: Userid5;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogTemplateRef".
 */
export interface LogTemplateRef {
  id: Id31;
  name: Name25;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogFeedOut".
 */
export interface LogFeedOut {
  entries?: Entries;
  nextCursor?: Nextcursor;
  pinned?: Pinned1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogFeedQuery".
 */
export interface LogFeedQuery {
  cursor?: Cursor;
  departmentId?: Departmentid16;
  from?: From1;
  mentioningMe?: Mentioningme;
  shift?: Shift | null;
  to?: To1;
}
/**
 * One row of the composer's picker — a person or a department, one flat list.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogMentionableOut".
 */
export interface LogMentionableOut {
  displayName: Displayname1;
  id: Id32;
  subtitle?: Subtitle;
  type: MentionTargetType;
}
/**
 * `id` set = update that field in place; omitted = a new field. A saved field missing from
 * the list is soft-deleted, and its type never changes (log templates spec §2.1).
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogTemplateFieldIn".
 */
export interface LogTemplateFieldIn {
  fieldType: LogFieldType;
  id?: Id33;
  label: Label3;
  required?: Required2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogTemplateFieldOut".
 */
export interface LogTemplateFieldOut {
  active: Active13;
  fieldType: LogFieldType;
  id: Id34;
  label: Label4;
  position: Position3;
  required: Required3;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogTemplateIn".
 */
export interface LogTemplateIn {
  active?: Active14;
  audience?: Audience;
  fields: Fields;
  name: Name26;
  shift?: Shift | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogTemplateOut".
 */
export interface LogTemplateOut {
  active: Active15;
  audience: Audience1;
  fields: Fields1;
  id: Id35;
  name: Name27;
  position: Position4;
  shift?: Shift | null;
  usedCount: Usedcount;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LogTemplatePatch".
 */
export interface LogTemplatePatch {
  active?: Active16;
  audience?: Audience2;
  fields?: Fields2;
  name?: Name28;
  shift?: Shift | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "LoginRequest".
 */
export interface LoginRequest {
  email: Email2;
  password: Password1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "MembershipOut".
 */
export interface MembershipOut {
  departmentId?: Departmentid17;
  departmentType?: DepartmentType | null;
  propertyCode: Propertycode;
  propertyId: Propertyid;
  propertyName: Propertyname1;
  role: Role;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "NotificationOut".
 */
export interface NotificationOut {
  body?: Body7;
  createdAt: Createdat7;
  entityId?: Entityid;
  entityType?: Entitytype;
  id: Id36;
  readAt?: Readat;
  title: Title2;
  type: Type;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "Overview".
 */
export interface Overview {
  conversations: Conversations;
  firstResponseDistribution: Firstresponsedistribution;
  firstResponseP50Seconds?: Firstresponsep50Seconds1;
  firstResponseP90Seconds?: Firstresponsep90Seconds1;
  inboundByDay: Inboundbyday;
  inboundByHour: Inboundbyhour;
  inboundMessages: Inboundmessages;
  meanTimeToResolveSeconds?: Meantimetoresolveseconds1;
  outboundMessages: Outboundmessages;
  since: Since;
  slaBreachRate: Slabreachrate;
  slaBreaches: Slabreaches1;
  until: Until;
  workOrdersByDepartment: Workordersbydepartment;
  workOrdersClosed: Workordersclosed;
  workOrdersCreated: Workorderscreated1;
  workOrdersFromConversations: Workordersfromconversations;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "ResponseBucket".
 */
export interface ResponseBucket {
  count: Count2;
  label: Label5;
  share: Share;
}
/**
 * Only the keys the client is allowed to set. `extra='forbid'` comes from CamelModel.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PrefsPatch".
 */
export interface PrefsPatch {
  theme?: Theme;
}
/**
 * Previews arbitrary body text, so the admin editor can render unsaved drafts.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PreviewRequest".
 */
export interface PreviewRequest {
  body: Body8;
  conversationId?: Conversationid1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PropertySettingsOut".
 */
export interface PropertySettingsOut {
  address?: Address;
  autoResolveHours: Autoresolvehours;
  brand?: Brand;
  code: Code1;
  currency: Currency;
  helpText?: Helptext;
  id: Id37;
  logoUrl?: Logourl;
  name: Name29;
  phone?: Phone2;
  primaryColor?: Primarycolor;
  slaMinutes: Slaminutes;
  smsNumber?: Smsnumber;
  timezone: Timezone;
}
/**
 * `code` is intentionally absent: it is unique across the whole install and identifies the
 * property, so renaming it is not a settings edit. `Property.settings` (an untyped JSON bag) is
 * intentionally absent too; its three live keys are exposed above as typed validated fields
 * instead (`slaMinutes`, `autoResolveHours`, `helpText`). `timezone`, `phone` and `sms_number`
 * carry only their column lengths here; their real validation lives in app/domain/properties.py
 * beside the reason each one is load-bearing.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "PropertySettingsPatch".
 */
export interface PropertySettingsPatch {
  address?: Address1;
  autoResolveHours?: Autoresolvehours1;
  brand?: Brand1;
  currency?: Currency1;
  helpText?: Helptext1;
  logoUrl?: Logourl1;
  name?: Name30;
  phone?: Phone3;
  primaryColor?: Primarycolor1;
  slaMinutes?: Slaminutes1;
  smsNumber?: Smsnumber1;
  timezone?: Timezone1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "QuickReplyIn".
 */
export interface QuickReplyIn {
  active?: Active17;
  body: Body9;
  category?: Category3;
  departmentId?: Departmentid18;
  locale?: Locale;
  shortcut: Shortcut;
  title: Title3;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "QuickReplyOut".
 */
export interface QuickReplyOut {
  active: Active18;
  body: Body10;
  category?: Category4;
  departmentId?: Departmentid19;
  id: Id38;
  locale: Locale1;
  shortcut: Shortcut1;
  title: Title4;
  usageCount: Usagecount;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "QuickReplyPatch".
 */
export interface QuickReplyPatch {
  active?: Active19;
  body?: Body11;
  category?: Category5;
  departmentId?: Departmentid20;
  locale?: Locale2;
  shortcut?: Shortcut2;
  title?: Title5;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "RenderRequest".
 */
export interface RenderRequest {
  conversationId: Conversationid2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "RenderedQuickReply".
 */
export interface RenderedQuickReply {
  body: Body12;
  characters: Characters;
  segments: Segments;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "RunOut".
 */
export interface RunOut {
  answers?: Answers1;
  completedAt?: Completedat4;
  cycleId?: Cycleid;
  dueAt?: Dueat1;
  id: Id39;
  inspectedAt?: Inspectedat2;
  inspectedByName?: Inspectedbyname2;
  inspectedByUserId?: Inspectedbyuserid;
  inspectionNote?: Inspectionnote1;
  items?: Items4;
  missingRequired?: Missingrequired1;
  photos?: Photos3;
  startedAt?: Startedat2;
  startedByName?: Startedbyname1;
  startedByUserId?: Startedbyuserid;
  status: PmRunStatus;
  templateId: Templateid4;
  templateName: Templatename3;
  unitCode: Unitcode1;
  unitId: Unitid2;
  unitKind: PmUnitKind;
  unitName: Unitname1;
  workOrderId?: Workorderid1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "TemplateItemOut".
 */
export interface TemplateItemOut {
  active: Active20;
  id: Id40;
  itemType: PmItemType;
  label: Label6;
  maxValue?: Maxvalue2;
  minValue?: Minvalue2;
  position: Position5;
  required: Required4;
  unit?: Unit2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SendMessageRequest".
 */
export interface SendMessageRequest {
  body: Body13;
  digitalAssetId?: Digitalassetid1;
  draftPromptId?: Draftpromptid;
}
/**
 * The non-file half of the multipart body; a `photo` file part arrives alongside it,
 * exactly like WorkOrderPhotoUpload.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SendStaffMessageRequest".
 */
export interface SendStaffMessageRequest {
  body?: Body14;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SessionOut".
 */
export interface SessionOut {
  memberships: Memberships;
  user: UserOut;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "UserOut".
 */
export interface UserOut {
  avatarUrl?: Avatarurl1;
  email: Email3;
  firstName: Firstname2;
  id: Id41;
  lastName: Lastname2;
  locale: Locale3;
  notificationPrefs?: Notificationprefs;
}
export interface Notificationprefs {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SimEvent".
 */
export interface SimEvent {
  at: At;
  payload: Payload;
  propertyId: Propertyid1;
  type: Type1;
}
export interface Payload {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SimGuest".
 */
export interface SimGuest {
  guestId: Guestid;
  inHouse: Inhouse;
  name: Name31;
  phone: Phone4;
  propertyId: Propertyid2;
  propertyName: Propertyname2;
  propertySmsNumber?: Propertysmsnumber;
  roomNumber?: Roomnumber2;
  smsConsentStatus: SmsConsentStatus;
  stayId?: Stayid;
  willFail: Willfail;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StaffConversationDetail".
 */
export interface StaffConversationDetail {
  avatarUrl?: Avatarurl2;
  createdAt: Createdat8;
  displayName: Displayname2;
  id: Id42;
  kind: StaffConversationKind;
  lastMessageAt?: Lastmessageat;
  lastMessagePreview?: Lastmessagepreview1;
  messages: Messages2;
  name?: Name32;
  otherUserId?: Otheruserid;
  participants: Participants;
  unread: Unread;
  updatedAt: Updatedat;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StaffMessageOut".
 */
export interface StaffMessageOut {
  authorName: Authorname2;
  authorUserId: Authoruserid3;
  body?: Body15;
  conversationId: Conversationid3;
  createdAt: Createdat9;
  id: Id43;
  photoUrl?: Photourl1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StaffParticipantOut".
 */
export interface StaffParticipantOut {
  avatarUrl?: Avatarurl3;
  departmentId?: Departmentid21;
  firstName: Firstname3;
  lastName: Lastname3;
  role: Role;
  userId: Userid6;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StaffConversationOut".
 */
export interface StaffConversationOut {
  avatarUrl?: Avatarurl4;
  createdAt: Createdat10;
  displayName: Displayname3;
  id: Id44;
  kind: StaffConversationKind;
  lastMessageAt?: Lastmessageat1;
  lastMessagePreview?: Lastmessagepreview2;
  name?: Name33;
  otherUserId?: Otheruserid1;
  participants: Participants1;
  unread: Unread1;
  updatedAt: Updatedat1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StaffDirectoryEntryOut".
 */
export interface StaffDirectoryEntryOut {
  avatarUrl?: Avatarurl5;
  departmentId?: Departmentid22;
  departmentName?: Departmentname5;
  firstName: Firstname4;
  lastName: Lastname4;
  role: Role;
  userId: Userid7;
}
/**
 * Per-property membership fields only.
 *
 * `UserAccount` is global and one account may hold memberships at several properties, so an
 * endpoint authorised by a membership at the property in the URL must never write global
 * columns (password, status, name): an admin at one property could otherwise reset the password
 * of an account that is also an admin somewhere else and inherit its access everywhere. Revoking
 * a person's access to *this* property is DELETE /users/<id> (the membership), not a global
 * account disable.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StaffPatch".
 */
export interface StaffPatch {
  departmentId?: Departmentid23;
  role?: Role | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StaffUserOut".
 */
export interface StaffUserOut {
  avatarUrl?: Avatarurl6;
  departmentId?: Departmentid24;
  email: Email4;
  firstName: Firstname5;
  id: Id45;
  lastName: Lastname5;
  role: Role;
  status: Status2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "StartRunRequest".
 */
export interface StartRunRequest {
  templateId: Templateid5;
  unitId: Unitid3;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SweepCounts".
 */
export interface SweepCounts {
  completed: Completed;
  remaining: Remaining;
  total: Total5;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SweepCycleOut".
 */
export interface SweepCycleOut {
  daysLeft: Daysleft1;
  endsOn: Endson2;
  id: Id46;
  ordinal: Ordinal2;
  startsOn: Startson2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SweepOut".
 */
export interface SweepOut {
  counts: SweepCounts;
  cycle?: SweepCycleOut | null;
  template?: SweepTemplateOut | null;
  units?: Units;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SweepTemplateOut".
 */
export interface SweepTemplateOut {
  cadence: PmCadence;
  id: Id47;
  name: Name34;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SweepUnitOut".
 */
export interface SweepUnitOut {
  code: Code2;
  currentRun?: SweepRunBrief | null;
  floor?: Floor1;
  id: Id49;
  lastPassedAt?: Lastpassedat;
  lastPassedByName?: Lastpassedbyname;
  name: Name35;
  passedThisCycle: Passedthiscycle;
  roomType?: Roomtype2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SweepRunBrief".
 */
export interface SweepRunBrief {
  id: Id48;
  startedByName?: Startedbyname2;
  startedByUserId?: Startedbyuserid1;
  status: PmRunStatus;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "SweepQuery".
 */
export interface SweepQuery {
  kind: PmUnitKind;
  q?: Q;
  sort?: Sort1;
  status?: Status3;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "TemplateIn".
 */
export interface TemplateIn {
  active?: Active21;
  cadence?: PmCadence | null;
  departmentId?: Departmentid25;
  items?: Items5;
  mode: PmTemplateMode;
  name: Name36;
  rrule?: Rrule;
  rruleDtstart?: Rruledtstart;
  unitIds?: Unitids;
  unitKind?: PmUnitKind | null;
}
/**
 * `id` set = update that item in place; omitted = a new item. An item missing from the
 * list is soft-deleted (spec §4.5).
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "TemplateItemIn".
 */
export interface TemplateItemIn {
  id?: Id50;
  itemType: PmItemType;
  label: Label7;
  maxValue?: Maxvalue3;
  minValue?: Minvalue3;
  required?: Required5;
  unit?: Unit3;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "TemplateOut".
 */
export interface TemplateOut {
  active: Active22;
  cadence?: PmCadence | null;
  createdAt: Createdat11;
  departmentId?: Departmentid26;
  hasRuns: Hasruns;
  id: Id51;
  items?: Items6;
  lastFiredAt?: Lastfiredat;
  mode: PmTemplateMode;
  name: Name37;
  rrule?: Rrule1;
  rruleDtstart?: Rruledtstart1;
  unitIds?: Unitids1;
  unitKind?: PmUnitKind | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "TemplatePatch".
 */
export interface TemplatePatch {
  active?: Active23;
  cadence?: PmCadence | null;
  departmentId?: Departmentid27;
  items?: Items7;
  mode?: PmTemplateMode | null;
  name?: Name38;
  rrule?: Rrule2;
  rruleDtstart?: Rruledtstart2;
  unitIds?: Unitids2;
  unitKind?: PmUnitKind | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "UnitImportError".
 */
export interface UnitImportError {
  field: Field;
  line: Line;
  message: Message;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "UnitImportOut".
 */
export interface UnitImportOut {
  created: Created;
  errors?: Errors;
  updated: Updated;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "UnitIn".
 */
export interface UnitIn {
  code: Code3;
  externalId?: Externalid;
  floor?: Floor2;
  kind: PmUnitKind;
  name: Name39;
  notes?: Notes3;
  roomType?: Roomtype3;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "UnitListQuery".
 */
export interface UnitListQuery {
  active?: Active24;
  kind?: PmUnitKind | null;
  q?: Q1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "UnitOut".
 */
export interface UnitOut {
  active: Active25;
  code: Code4;
  createdAt: Createdat12;
  externalId?: Externalid1;
  floor?: Floor3;
  id: Id52;
  kind: PmUnitKind;
  name: Name40;
  notes?: Notes4;
  roomType?: Roomtype4;
  source: PmUnitSource;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "UnitPatch".
 */
export interface UnitPatch {
  active?: Active26;
  code?: Code5;
  externalId?: Externalid2;
  floor?: Floor4;
  kind?: PmUnitKind | null;
  name?: Name41;
  notes?: Notes5;
  roomType?: Roomtype5;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "UnreadCount".
 */
export interface UnreadCount {
  count: Count3;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderDetail".
 */
export interface WorkOrderDetail {
  acknowledgedAt?: Acknowledgedat1;
  assignedUserId?: Assigneduserid7;
  completedAt?: Completedat5;
  createdAt: Createdat13;
  departmentId?: Departmentid28;
  description?: Description4;
  dueAt?: Dueat2;
  events: Events1;
  guestName?: Guestname1;
  guestNotifiedAt?: Guestnotifiedat1;
  id: Id54;
  locationRef?: Locationref1;
  locationType: LocationType1;
  photos: Photos4;
  pmRunId?: Pmrunid;
  priority: Priority;
  reportedByUserId?: Reportedbyuserid;
  roomNumber?: Roomnumber3;
  sourceConversationId?: Sourceconversationid1;
  sourceMessageId?: Sourcemessageid1;
  startedAt?: Startedat3;
  status: WorkOrderStatus;
  title: Title6;
  type: WorkOrderType;
  updatedAt: Updatedat2;
  verifiedAt?: Verifiedat;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderEventOut".
 */
export interface WorkOrderEventOut {
  comment?: Comment3;
  createdAt: Createdat14;
  fromValue?: Fromvalue1;
  id: Id53;
  toValue?: Tovalue1;
  type: WorkOrderEventType;
  userId?: Userid8;
  userName?: Username1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderPhotoOut".
 */
export interface WorkOrderPhotoOut {
  byteSize: Bytesize2;
  contentType: Contenttype2;
  createdAt: Createdat15;
  id: Id55;
  kind: WorkOrderPhotoKind;
  uploadedByName?: Uploadedbyname;
  uploadedByUserId?: Uploadedbyuserid1;
  url: Url5;
  workOrderId: Workorderid2;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderListQuery".
 */
export interface WorkOrderListQuery {
  assignee?: Assignee;
  dept?: Dept1;
  includeClosed?: Includeclosed;
  mine?: Mine;
  status?: Status4;
  type?: WorkOrderType | null;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderOut".
 */
export interface WorkOrderOut {
  acknowledgedAt?: Acknowledgedat2;
  assignedUserId?: Assigneduserid8;
  completedAt?: Completedat6;
  createdAt: Createdat16;
  departmentId?: Departmentid29;
  description?: Description5;
  dueAt?: Dueat3;
  guestNotifiedAt?: Guestnotifiedat2;
  id: Id56;
  locationRef?: Locationref2;
  locationType: LocationType1;
  priority: Priority;
  reportedByUserId?: Reportedbyuserid1;
  sourceConversationId?: Sourceconversationid2;
  sourceMessageId?: Sourcemessageid2;
  startedAt?: Startedat4;
  status: WorkOrderStatus;
  title: Title7;
  type: WorkOrderType;
  updatedAt: Updatedat3;
  verifiedAt?: Verifiedat1;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderPatch".
 */
export interface WorkOrderPatch {
  assignedUserId?: Assigneduserid9;
  clearAssignee?: Clearassignee;
  comment?: Comment4;
  departmentId?: Departmentid30;
  priority?: Priority | null;
  status?: WorkOrderStatus | null;
}
/**
 * The non-file half of the multipart body. The file itself arrives as the `photo` part.
 *
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderPhotoUpload".
 */
export interface WorkOrderPhotoUpload {
  kind: WorkOrderPhotoKind;
}
/**
 * This interface was referenced by `RelayAPI`'s JSON-Schema
 * via the `definition` "WorkOrderPrefill".
 */
export interface WorkOrderPrefill {
  departmentId?: Departmentid31;
  description: Description6;
  guestName?: Guestname2;
  locationRef?: Locationref3;
  locationType: LocationType1;
  priority: Priority;
  sourceConversationId: Sourceconversationid3;
  sourceMessageId?: Sourcemessageid3;
  title: Title8;
  type: WorkOrderType;
}
