/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Conversationshandled = number;
export type Firstresponsep50Seconds = number | null;
export type Firstresponsep90Seconds = number | null;
export type Messagessent = number;
export type Name = string;
export type Quickreplyshare = number | null;
export type Slabreaches = number;
export type Userid = string;
export type Workorderscreated = number;
export type Active = boolean;
export type Category = string | null;
export type Departmentid = string | null;
export type Description = string | null;
export type Name1 = string;
export type Thumbnailurl = string | null;
export type AssetType = 'file' | 'link' | 'menu' | 'map' | 'form';
export type Url = string;
export type Validfrom = string | null;
export type Validuntil = string | null;
export type Active1 = boolean;
export type Category1 = string | null;
export type Departmentid1 = string | null;
export type Description1 = string | null;
export type Id = string;
export type Name2 = string;
export type Sendcount = number;
export type Shortcode = string;
export type Thumbnailurl1 = string | null;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "AssetType".
 */
export type AssetType1 = 'file' | 'link' | 'menu' | 'map' | 'form';
export type Url1 = string;
export type Validfrom1 = string | null;
export type Validuntil1 = string | null;
export type Active2 = boolean | null;
export type Category2 = string | null;
export type Departmentid2 = string | null;
export type Description2 = string | null;
export type Name3 = string | null;
export type Thumbnailurl2 = string | null;
export type Url2 = string | null;
export type Validfrom2 = string | null;
export type Validuntil2 = string | null;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "AuthorType".
 */
export type AuthorType = 'guest' | 'staff' | 'system' | 'automation';
export type Active3 = boolean;
export type Name4 = string;
export type Parentid = string | null;
export type Active4 = boolean;
export type Children = CategoryOut[];
export type Id1 = string;
export type Name5 = string;
export type Parentid1 = string | null;
export type Active5 = boolean | null;
export type Name6 = string | null;
export type Parentid2 = string | null;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "Channel".
 */
export type Channel = 'sms' | 'web' | 'whatsapp' | 'email';
export type Archivedat = string | null;
export type Assigneddepartmentid = string | null;
export type Assigneduserid = string | null;
export type Body = string;
export type Createdat = string;
export type Id2 = string;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "DraftPromptStatus".
 */
export type DraftPromptStatus = 'pending' | 'sent' | 'dismissed';
export type Workorderid = string;
export type Workordertitle = string;
export type Draftprompts = DraftPromptOut[];
export type Firstresponseseconds = number | null;
export type Email = string | null;
export type Firstname = string | null;
export type Id3 = string;
export type Lastname = string | null;
export type Loyaltytier = string | null;
export type Notessummary = string | null;
export type Phonee164 = string;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "SmsConsentStatus".
 */
export type SmsConsentStatus = 'unknown' | 'opted_in' | 'opted_out';
export type Vip = boolean;
export type Id4 = string;
export type Lastguestmessageat = string | null;
export type Laststaffmessageat = string | null;
export type Authoruserid = string | null;
export type Body1 = string;
export type Conversationid = string;
export type Deliveredat = string | null;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "DeliveryStatus".
 */
export type DeliveryStatus = 'queued' | 'sent' | 'delivered' | 'failed' | 'undelivered';
export type Digitalassetid = string | null;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "Direction".
 */
export type Direction = 'inbound' | 'outbound';
export type Id5 = string;
export type Providererrorcode = string | null;
export type Providererrormessage = string | null;
export type Redacted = boolean;
export type Sentat = string | null;
export type Messages = MessageOut[];
export type Authorname = string;
export type Authoruserid1 = string;
export type Body2 = string;
export type Createdat1 = string;
export type Id6 = string;
export type Mentions = string[];
export type Notes = NoteOut[];
export type Resolutioncategoryid = string | null;
export type Sladueat = string | null;
export type Snoozeduntil = string | null;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "ConversationStatus".
 */
export type ConversationStatus = 'open' | 'snoozed' | 'archived';
export type Adults = number;
export type Arrivaldate = string;
export type Children1 = number;
export type Departuredate = string;
export type Id7 = string;
export type Isreturnguest = boolean;
export type Roomnumber = string | null;
export type Roomtype = string | null;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "StayStatus".
 */
export type StayStatus = 'reserved' | 'checked_in' | 'checked_out' | 'cancelled' | 'no_show';
export type Staycount = number;
export type Assigneduserid1 = string | null;
export type Completedat = string | null;
export type Createdat2 = string;
export type Departmentid3 = string | null;
export type Guestnotifiedat = string | null;
export type Id8 = string;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "Priority".
 */
export type Priority = 'low' | 'normal' | 'high' | 'urgent';
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderStatus".
 */
export type WorkOrderStatus = 'open' | 'assigned' | 'in_progress' | 'blocked' | 'complete' | 'verified' | 'cancelled';
export type Title = string;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderType".
 */
export type WorkOrderType = 'maintenance' | 'housekeeping' | 'guest_request' | 'pm' | 'other';
export type Workorders = WorkOrderBrief[];
export type Assigneddepartmentid1 = string | null;
export type Assigneduserid2 = string | null;
export type Clearassignment = boolean;
export type Resolutioncategoryid1 = string | null;
export type Snoozeduntil1 = string | null;
export type Assigneddepartmentid2 = string | null;
export type Assigneduserid3 = string | null;
export type Id9 = string;
export type Lastguestmessageat1 = string | null;
export type Lastmessagepreview = string | null;
export type Laststaffmessageat1 = string | null;
export type Openworkordercount = number;
export type Roomnumber1 = string | null;
export type Sladueat1 = string | null;
export type Snoozeduntil2 = string | null;
export type Unanswered = boolean;
export type Body3 = string;
export type Departmentid4 = string | null;
export type Email1 = string;
export type Firstname1 = string;
export type Lastname1 = string;
export type Password = string | null;
export type Phone = string | null;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "Role".
 */
export type Role = 'agent' | 'dept_staff' | 'supervisor' | 'manager' | 'admin' | 'corporate';
export type Assigneduserid4 = string | null;
export type Departmentid5 = string | null;
export type Description3 = string | null;
export type Dueat = string | null;
export type Locationref = string | null;
export type LocationType = 'room' | 'public_area' | 'equipment' | 'other';
export type Priority1 = 'low' | 'normal' | 'high' | 'urgent';
export type Sourceconversationid = string | null;
export type Sourcemessageid = string | null;
export type Title1 = string;
export type WorkOrderType1 = 'maintenance' | 'housekeeping' | 'guest_request' | 'pm' | 'other';
export type Count = number;
export type Day = string;
export type Closed = number;
export type Departmentid6 = string | null;
export type Departmentname = string;
export type Meantimetoresolveseconds = number | null;
export type Active6 = boolean;
export type Escalationminutes = number;
export type Name7 = string;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "DepartmentType".
 */
export type DepartmentType =
  'front_desk' | 'housekeeping' | 'engineering' | 'food_beverage' | 'spa' | 'security' | 'valet' | 'other';
export type Active7 = boolean;
export type Escalationminutes1 = number;
export type Id10 = string;
export type Name8 = string;
export type Active8 = boolean | null;
export type Escalationminutes2 = number | null;
export type Name9 = string | null;
export type Conversationids = string[];
export type Stays = StayOut[];
export type Body4 = string;
export type Id11 = string;
export type Sentat1 = string | null;
export type Messages1 = GuestThreadMessage[];
export type Phone1 = string;
export type Propertyname = string;
export type Count1 = number;
export type Hour = number;
export type Dept = string | null;
export type Filter = string;
export type Limit = number;
export type Offset = number;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "LocationType".
 */
export type LocationType1 = 'room' | 'public_area' | 'equipment' | 'other';
export type Email2 = string;
export type Password1 = string;
export type Departmentid7 = string | null;
export type Propertycode = string;
export type Propertyid = string;
export type Propertyname1 = string;
export type Body5 = string | null;
export type Createdat3 = string;
export type Entityid = string | null;
export type Entitytype = string | null;
export type Id12 = string;
export type Readat = string | null;
export type Title2 = string;
export type Type = string;
export type Conversations = number;
export type Count2 = number;
export type Label = string;
export type Share = number;
export type Firstresponsedistribution = ResponseBucket[];
export type Firstresponsep50Seconds1 = number | null;
export type Firstresponsep90Seconds1 = number | null;
export type Inboundbyday = DayBucket[];
export type Inboundbyhour = HourBucket[];
export type Inboundmessages = number;
export type Meantimetoresolveseconds1 = number | null;
export type Outboundmessages = number;
export type Since = string;
export type Slabreachrate = number;
export type Slabreaches1 = number;
export type Until = string;
export type Workordersbydepartment = DepartmentBucket[];
export type Workordersclosed = number;
export type Workorderscreated1 = number;
export type Workordersfromconversations = number;
export type Theme = ('dark' | 'light' | 'system') | null;
export type Body6 = string;
export type Conversationid1 = string | null;
export type Address = string | null;
export type Autoresolvehours = number;
export type Brand = string | null;
export type Code = string;
export type Currency = string;
export type Helptext = string | null;
export type Id13 = string;
export type Logourl = string | null;
export type Name10 = string;
export type Phone2 = string | null;
export type Primarycolor = string | null;
export type Slaminutes = number;
export type Smsnumber = string | null;
export type Timezone = string;
export type Address1 = string | null;
export type Autoresolvehours1 = number | null;
export type Brand1 = string | null;
export type Currency1 = string | null;
export type Helptext1 = string | null;
export type Logourl1 = string | null;
export type Name11 = string | null;
export type Phone3 = string | null;
export type Primarycolor1 = string | null;
export type Slaminutes1 = number | null;
export type Smsnumber1 = string | null;
export type Timezone1 = string | null;
export type Active9 = boolean;
export type Body7 = string;
export type Category3 = string | null;
export type Departmentid8 = string | null;
export type Locale = string;
export type Shortcut = string;
export type Title3 = string;
export type Active10 = boolean;
export type Body8 = string;
export type Category4 = string | null;
export type Departmentid9 = string | null;
export type Id14 = string;
export type Locale1 = string;
export type Shortcut1 = string;
export type Title4 = string;
export type Usagecount = number;
export type Active11 = boolean | null;
export type Body9 = string | null;
export type Category5 = string | null;
export type Departmentid10 = string | null;
export type Locale2 = string | null;
export type Shortcut2 = string | null;
export type Title5 = string | null;
export type Conversationid2 = string;
export type Body10 = string;
export type Characters = number;
export type Segments = number;
export type Body11 = string;
export type Digitalassetid1 = string | null;
export type Draftpromptid = string | null;
export type Memberships = MembershipOut[];
export type Avatarurl = string | null;
export type Email3 = string;
export type Firstname2 = string;
export type Id15 = string;
export type Lastname2 = string;
export type Locale3 = string;
export type At = string;
export type Propertyid1 = string;
export type Type1 = string;
export type Guestid = string;
export type Inhouse = boolean;
export type Name12 = string;
export type Phone4 = string;
export type Propertyid2 = string;
export type Propertyname2 = string;
export type Propertysmsnumber = string | null;
export type Roomnumber2 = string | null;
export type Willfail = boolean;
export type Departmentid11 = string | null;
export type Avatarurl1 = string | null;
export type Departmentid12 = string | null;
export type Email4 = string;
export type Firstname3 = string;
export type Id16 = string;
export type Lastname3 = string;
export type Status = string;
export type Count3 = number;
export type Acknowledgedat = string | null;
export type Assigneduserid5 = string | null;
export type Completedat1 = string | null;
export type Createdat4 = string;
export type Departmentid13 = string | null;
export type Description4 = string | null;
export type Dueat1 = string | null;
export type Comment = string | null;
export type Createdat5 = string;
export type Fromvalue = string | null;
export type Id17 = string;
export type Tovalue = string | null;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderEventType".
 */
export type WorkOrderEventType =
  'created' | 'status_changed' | 'assigned' | 'commented' | 'priority_changed' | 'photo_attached';
export type Userid1 = string | null;
export type Username = string | null;
export type Events = WorkOrderEventOut[];
export type Guestname = string | null;
export type Guestnotifiedat1 = string | null;
export type Id18 = string;
export type Locationref1 = string | null;
export type Bytesize = number;
export type Contenttype = string;
export type Createdat6 = string;
export type Id19 = string;
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderPhotoKind".
 */
export type WorkOrderPhotoKind = 'before' | 'after';
export type Uploadedbyname = string | null;
export type Uploadedbyuserid = string | null;
export type Url3 = string;
export type Workorderid1 = string;
export type Photos = WorkOrderPhotoOut[];
export type Reportedbyuserid = string | null;
export type Roomnumber3 = string | null;
export type Sourceconversationid1 = string | null;
export type Sourcemessageid1 = string | null;
export type Startedat = string | null;
export type Title6 = string;
export type Updatedat = string;
export type Verifiedat = string | null;
export type Assignee = string | null;
export type Dept1 = string | null;
export type Includeclosed = boolean;
export type Mine = boolean;
export type Status1 = string | null;
export type Acknowledgedat1 = string | null;
export type Assigneduserid6 = string | null;
export type Completedat2 = string | null;
export type Createdat7 = string;
export type Departmentid14 = string | null;
export type Description5 = string | null;
export type Dueat2 = string | null;
export type Guestnotifiedat2 = string | null;
export type Id20 = string;
export type Locationref2 = string | null;
export type Reportedbyuserid1 = string | null;
export type Sourceconversationid2 = string | null;
export type Sourcemessageid2 = string | null;
export type Startedat1 = string | null;
export type Title7 = string;
export type Updatedat1 = string;
export type Verifiedat1 = string | null;
export type Assigneduserid7 = string | null;
export type Clearassignee = boolean;
export type Comment1 = string | null;
export type Departmentid15 = string | null;
export type Departmentid16 = string | null;
export type Description6 = string;
export type Guestname1 = string | null;
export type Locationref3 = string | null;
export type Sourceconversationid3 = string;
export type Sourcemessageid3 = string | null;
export type Title8 = string;

export interface ConciergeAPI {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "AgentStats".
 */
export interface AgentStats {
  conversationsHandled: Conversationshandled;
  firstResponseP50Seconds?: Firstresponsep50Seconds;
  firstResponseP90Seconds?: Firstresponsep90Seconds;
  messagesSent: Messagessent;
  name: Name;
  quickReplyShare?: Quickreplyshare;
  slaBreaches: Slabreaches;
  userId: Userid;
  workOrdersCreated: Workorderscreated;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "AssetIn".
 */
export interface AssetIn {
  active?: Active;
  category?: Category;
  departmentId?: Departmentid;
  description?: Description;
  name: Name1;
  thumbnailUrl?: Thumbnailurl;
  type?: AssetType;
  url: Url;
  validFrom?: Validfrom;
  validUntil?: Validuntil;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "AssetOut".
 */
export interface AssetOut {
  active: Active1;
  category?: Category1;
  departmentId?: Departmentid1;
  description?: Description1;
  id: Id;
  name: Name2;
  sendCount: Sendcount;
  shortCode: Shortcode;
  thumbnailUrl?: Thumbnailurl1;
  type: AssetType1;
  url: Url1;
  validFrom?: Validfrom1;
  validUntil?: Validuntil1;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "AssetPatch".
 */
export interface AssetPatch {
  active?: Active2;
  category?: Category2;
  departmentId?: Departmentid2;
  description?: Description2;
  name?: Name3;
  thumbnailUrl?: Thumbnailurl2;
  type?: AssetType1 | null;
  url?: Url2;
  validFrom?: Validfrom2;
  validUntil?: Validuntil2;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "CategoryIn".
 */
export interface CategoryIn {
  active?: Active3;
  name: Name4;
  parentId?: Parentid;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "CategoryOut".
 */
export interface CategoryOut {
  active: Active4;
  children?: Children;
  id: Id1;
  name: Name5;
  parentId?: Parentid1;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "CategoryPatch".
 */
export interface CategoryPatch {
  active?: Active5;
  name?: Name6;
  parentId?: Parentid2;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "ConversationDetail".
 */
export interface ConversationDetail {
  archivedAt?: Archivedat;
  assignedDepartmentId?: Assigneddepartmentid;
  assignedUserId?: Assigneduserid;
  channelPrimary: Channel;
  draftPrompts: Draftprompts;
  firstResponseSeconds?: Firstresponseseconds;
  guest: GuestOut;
  id: Id4;
  lastGuestMessageAt?: Lastguestmessageat;
  lastStaffMessageAt?: Laststaffmessageat;
  messages: Messages;
  notes: Notes;
  resolutionCategoryId?: Resolutioncategoryid;
  slaDueAt?: Sladueat;
  snoozedUntil?: Snoozeduntil;
  status: ConversationStatus;
  stay?: StayOut | null;
  workOrders: Workorders;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "DraftPromptOut".
 */
export interface DraftPromptOut {
  body: Body;
  createdAt: Createdat;
  id: Id2;
  status: DraftPromptStatus;
  workOrderId: Workorderid;
  workOrderTitle: Workordertitle;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "GuestOut".
 */
export interface GuestOut {
  email?: Email;
  firstName?: Firstname;
  id: Id3;
  lastName?: Lastname;
  loyaltyTier?: Loyaltytier;
  notesSummary?: Notessummary;
  phoneE164: Phonee164;
  smsConsentStatus: SmsConsentStatus;
  vip: Vip;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "MessageOut".
 */
export interface MessageOut {
  authorType: AuthorType;
  authorUserId?: Authoruserid;
  body: Body1;
  channel: Channel;
  conversationId: Conversationid;
  deliveredAt?: Deliveredat;
  deliveryStatus: DeliveryStatus;
  digitalAssetId?: Digitalassetid;
  direction: Direction;
  id: Id5;
  providerErrorCode?: Providererrorcode;
  providerErrorMessage?: Providererrormessage;
  redacted: Redacted;
  sentAt?: Sentat;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "NoteOut".
 */
export interface NoteOut {
  authorName: Authorname;
  authorUserId: Authoruserid1;
  body: Body2;
  createdAt: Createdat1;
  id: Id6;
  mentions: Mentions;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "StayOut".
 */
export interface StayOut {
  adults: Adults;
  arrivalDate: Arrivaldate;
  children: Children1;
  departureDate: Departuredate;
  id: Id7;
  isReturnGuest: Isreturnguest;
  roomNumber?: Roomnumber;
  roomType?: Roomtype;
  status: StayStatus;
  stayCount: Staycount;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderBrief".
 */
export interface WorkOrderBrief {
  assignedUserId?: Assigneduserid1;
  completedAt?: Completedat;
  createdAt: Createdat2;
  departmentId?: Departmentid3;
  guestNotifiedAt?: Guestnotifiedat;
  id: Id8;
  priority: Priority;
  status: WorkOrderStatus;
  title: Title;
  type: WorkOrderType;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "ConversationPatch".
 */
export interface ConversationPatch {
  assignedDepartmentId?: Assigneddepartmentid1;
  assignedUserId?: Assigneduserid2;
  clearAssignment?: Clearassignment;
  resolutionCategoryId?: Resolutioncategoryid1;
  snoozedUntil?: Snoozeduntil1;
  status?: ConversationStatus | null;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "ConversationSummary".
 */
export interface ConversationSummary {
  assignedDepartmentId?: Assigneddepartmentid2;
  assignedUserId?: Assigneduserid3;
  channelPrimary: Channel;
  guest: GuestOut;
  id: Id9;
  lastGuestMessageAt?: Lastguestmessageat1;
  lastMessagePreview?: Lastmessagepreview;
  lastStaffMessageAt?: Laststaffmessageat1;
  openWorkOrderCount: Openworkordercount;
  roomNumber?: Roomnumber1;
  slaDueAt?: Sladueat1;
  snoozedUntil?: Snoozeduntil2;
  status: ConversationStatus;
  unanswered: Unanswered;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "CreateNoteRequest".
 */
export interface CreateNoteRequest {
  body: Body3;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "CreateStaffRequest".
 */
export interface CreateStaffRequest {
  departmentId?: Departmentid4;
  email: Email1;
  firstName: Firstname1;
  lastName: Lastname1;
  password?: Password;
  phone?: Phone;
  role: Role;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "CreateWorkOrder".
 */
export interface CreateWorkOrder {
  assignedUserId?: Assigneduserid4;
  departmentId?: Departmentid5;
  description?: Description3;
  dueAt?: Dueat;
  locationRef?: Locationref;
  locationType?: LocationType;
  priority?: Priority1;
  sourceConversationId?: Sourceconversationid;
  sourceMessageId?: Sourcemessageid;
  title: Title1;
  type?: WorkOrderType1;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "DayBucket".
 */
export interface DayBucket {
  count: Count;
  day: Day;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "DepartmentBucket".
 */
export interface DepartmentBucket {
  closed: Closed;
  departmentId?: Departmentid6;
  departmentName: Departmentname;
  meanTimeToResolveSeconds?: Meantimetoresolveseconds;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "DepartmentIn".
 */
export interface DepartmentIn {
  active?: Active6;
  escalationMinutes?: Escalationminutes;
  name: Name7;
  type: DepartmentType;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "DepartmentOut".
 */
export interface DepartmentOut {
  active: Active7;
  escalationMinutes: Escalationminutes1;
  id: Id10;
  name: Name8;
  type: DepartmentType;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "DepartmentPatch".
 */
export interface DepartmentPatch {
  active?: Active8;
  escalationMinutes?: Escalationminutes2;
  name?: Name9;
  type?: DepartmentType | null;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "GuestDetail".
 */
export interface GuestDetail {
  conversationIds: Conversationids;
  guest: GuestOut;
  stays: Stays;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "GuestThread".
 */
export interface GuestThread {
  messages: Messages1;
  phone: Phone1;
  propertyName: Propertyname;
}
/**
 * What a guest could ever see. Deliberately has no field that could carry an internal note.
 *
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "GuestThreadMessage".
 */
export interface GuestThreadMessage {
  body: Body4;
  deliveryStatus: DeliveryStatus;
  direction: Direction;
  id: Id11;
  sentAt?: Sentat1;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "HourBucket".
 */
export interface HourBucket {
  count: Count1;
  hour: Hour;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "ListQuery".
 */
export interface ListQuery {
  dept?: Dept;
  filter?: Filter;
  limit?: Limit;
  offset?: Offset;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "LoginRequest".
 */
export interface LoginRequest {
  email: Email2;
  password: Password1;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "MembershipOut".
 */
export interface MembershipOut {
  departmentId?: Departmentid7;
  propertyCode: Propertycode;
  propertyId: Propertyid;
  propertyName: Propertyname1;
  role: Role;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "NotificationOut".
 */
export interface NotificationOut {
  body?: Body5;
  createdAt: Createdat3;
  entityId?: Entityid;
  entityType?: Entitytype;
  id: Id12;
  readAt?: Readat;
  title: Title2;
  type: Type;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "Overview".
 */
export interface Overview {
  conversations: Conversations;
  firstResponseDistribution: Firstresponsedistribution;
  firstResponseP50Seconds?: Firstresponsep50Seconds1;
  firstResponseP90Seconds?: Firstresponsep90Seconds1;
  inboundByDay: Inboundbyday;
  inboundByHour: Inboundbyhour;
  inboundMessages: Inboundmessages;
  meanTimeToResolveSeconds?: Meantimetoresolveseconds1;
  outboundMessages: Outboundmessages;
  since: Since;
  slaBreachRate: Slabreachrate;
  slaBreaches: Slabreaches1;
  until: Until;
  workOrdersByDepartment: Workordersbydepartment;
  workOrdersClosed: Workordersclosed;
  workOrdersCreated: Workorderscreated1;
  workOrdersFromConversations: Workordersfromconversations;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "ResponseBucket".
 */
export interface ResponseBucket {
  count: Count2;
  label: Label;
  share: Share;
}
/**
 * Only the keys the client is allowed to set. `extra='forbid'` comes from CamelModel.
 *
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "PrefsPatch".
 */
export interface PrefsPatch {
  theme?: Theme;
}
/**
 * Previews arbitrary body text, so the admin editor can render unsaved drafts.
 *
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "PreviewRequest".
 */
export interface PreviewRequest {
  body: Body6;
  conversationId?: Conversationid1;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "PropertySettingsOut".
 */
export interface PropertySettingsOut {
  address?: Address;
  autoResolveHours: Autoresolvehours;
  brand?: Brand;
  code: Code;
  currency: Currency;
  helpText?: Helptext;
  id: Id13;
  logoUrl?: Logourl;
  name: Name10;
  phone?: Phone2;
  primaryColor?: Primarycolor;
  slaMinutes: Slaminutes;
  smsNumber?: Smsnumber;
  timezone: Timezone;
}
/**
 * `code` is intentionally absent: it is unique across the whole install and identifies the
 * property, so renaming it is not a settings edit. `Property.settings` (an untyped JSON bag) is
 * intentionally absent too; its three live keys are exposed above as typed validated fields
 * instead (`slaMinutes`, `autoResolveHours`, `helpText`). `timezone`, `phone` and `sms_number`
 * carry only their column lengths here; their real validation lives in app/domain/properties.py
 * beside the reason each one is load-bearing.
 *
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "PropertySettingsPatch".
 */
export interface PropertySettingsPatch {
  address?: Address1;
  autoResolveHours?: Autoresolvehours1;
  brand?: Brand1;
  currency?: Currency1;
  helpText?: Helptext1;
  logoUrl?: Logourl1;
  name?: Name11;
  phone?: Phone3;
  primaryColor?: Primarycolor1;
  slaMinutes?: Slaminutes1;
  smsNumber?: Smsnumber1;
  timezone?: Timezone1;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "QuickReplyIn".
 */
export interface QuickReplyIn {
  active?: Active9;
  body: Body7;
  category?: Category3;
  departmentId?: Departmentid8;
  locale?: Locale;
  shortcut: Shortcut;
  title: Title3;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "QuickReplyOut".
 */
export interface QuickReplyOut {
  active: Active10;
  body: Body8;
  category?: Category4;
  departmentId?: Departmentid9;
  id: Id14;
  locale: Locale1;
  shortcut: Shortcut1;
  title: Title4;
  usageCount: Usagecount;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "QuickReplyPatch".
 */
export interface QuickReplyPatch {
  active?: Active11;
  body?: Body9;
  category?: Category5;
  departmentId?: Departmentid10;
  locale?: Locale2;
  shortcut?: Shortcut2;
  title?: Title5;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "RenderRequest".
 */
export interface RenderRequest {
  conversationId: Conversationid2;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "RenderedQuickReply".
 */
export interface RenderedQuickReply {
  body: Body10;
  characters: Characters;
  segments: Segments;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "SendMessageRequest".
 */
export interface SendMessageRequest {
  body: Body11;
  digitalAssetId?: Digitalassetid1;
  draftPromptId?: Draftpromptid;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "SessionOut".
 */
export interface SessionOut {
  memberships: Memberships;
  user: UserOut;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "UserOut".
 */
export interface UserOut {
  avatarUrl?: Avatarurl;
  email: Email3;
  firstName: Firstname2;
  id: Id15;
  lastName: Lastname2;
  locale: Locale3;
  notificationPrefs?: Notificationprefs;
}
export interface Notificationprefs {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "SimEvent".
 */
export interface SimEvent {
  at: At;
  payload: Payload;
  propertyId: Propertyid1;
  type: Type1;
}
export interface Payload {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "SimGuest".
 */
export interface SimGuest {
  guestId: Guestid;
  inHouse: Inhouse;
  name: Name12;
  phone: Phone4;
  propertyId: Propertyid2;
  propertyName: Propertyname2;
  propertySmsNumber?: Propertysmsnumber;
  roomNumber?: Roomnumber2;
  smsConsentStatus: SmsConsentStatus;
  willFail: Willfail;
}
/**
 * Per-property membership fields only.
 *
 * `UserAccount` is global and one account may hold memberships at several properties, so an
 * endpoint authorised by a membership at the property in the URL must never write global
 * columns (password, status, name): an admin at one property could otherwise reset the password
 * of an account that is also an admin somewhere else and inherit its access everywhere. Revoking
 * a person's access to *this* property is DELETE /users/<id> (the membership), not a global
 * account disable.
 *
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "StaffPatch".
 */
export interface StaffPatch {
  departmentId?: Departmentid11;
  role?: Role | null;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "StaffUserOut".
 */
export interface StaffUserOut {
  avatarUrl?: Avatarurl1;
  departmentId?: Departmentid12;
  email: Email4;
  firstName: Firstname3;
  id: Id16;
  lastName: Lastname3;
  role: Role;
  status: Status;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "UnreadCount".
 */
export interface UnreadCount {
  count: Count3;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderDetail".
 */
export interface WorkOrderDetail {
  acknowledgedAt?: Acknowledgedat;
  assignedUserId?: Assigneduserid5;
  completedAt?: Completedat1;
  createdAt: Createdat4;
  departmentId?: Departmentid13;
  description?: Description4;
  dueAt?: Dueat1;
  events: Events;
  guestName?: Guestname;
  guestNotifiedAt?: Guestnotifiedat1;
  id: Id18;
  locationRef?: Locationref1;
  locationType: LocationType1;
  photos: Photos;
  priority: Priority;
  reportedByUserId?: Reportedbyuserid;
  roomNumber?: Roomnumber3;
  sourceConversationId?: Sourceconversationid1;
  sourceMessageId?: Sourcemessageid1;
  startedAt?: Startedat;
  status: WorkOrderStatus;
  title: Title6;
  type: WorkOrderType;
  updatedAt: Updatedat;
  verifiedAt?: Verifiedat;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderEventOut".
 */
export interface WorkOrderEventOut {
  comment?: Comment;
  createdAt: Createdat5;
  fromValue?: Fromvalue;
  id: Id17;
  toValue?: Tovalue;
  type: WorkOrderEventType;
  userId?: Userid1;
  userName?: Username;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderPhotoOut".
 */
export interface WorkOrderPhotoOut {
  byteSize: Bytesize;
  contentType: Contenttype;
  createdAt: Createdat6;
  id: Id19;
  kind: WorkOrderPhotoKind;
  uploadedByName?: Uploadedbyname;
  uploadedByUserId?: Uploadedbyuserid;
  url: Url3;
  workOrderId: Workorderid1;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderListQuery".
 */
export interface WorkOrderListQuery {
  assignee?: Assignee;
  dept?: Dept1;
  includeClosed?: Includeclosed;
  mine?: Mine;
  status?: Status1;
  type?: WorkOrderType | null;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderOut".
 */
export interface WorkOrderOut {
  acknowledgedAt?: Acknowledgedat1;
  assignedUserId?: Assigneduserid6;
  completedAt?: Completedat2;
  createdAt: Createdat7;
  departmentId?: Departmentid14;
  description?: Description5;
  dueAt?: Dueat2;
  guestNotifiedAt?: Guestnotifiedat2;
  id: Id20;
  locationRef?: Locationref2;
  locationType: LocationType1;
  priority: Priority;
  reportedByUserId?: Reportedbyuserid1;
  sourceConversationId?: Sourceconversationid2;
  sourceMessageId?: Sourcemessageid2;
  startedAt?: Startedat1;
  status: WorkOrderStatus;
  title: Title7;
  type: WorkOrderType;
  updatedAt: Updatedat1;
  verifiedAt?: Verifiedat1;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderPatch".
 */
export interface WorkOrderPatch {
  assignedUserId?: Assigneduserid7;
  clearAssignee?: Clearassignee;
  comment?: Comment1;
  departmentId?: Departmentid15;
  priority?: Priority | null;
  status?: WorkOrderStatus | null;
}
/**
 * The non-file half of the multipart body. The file itself arrives as the `photo` part.
 *
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderPhotoUpload".
 */
export interface WorkOrderPhotoUpload {
  kind: WorkOrderPhotoKind;
}
/**
 * This interface was referenced by `ConciergeAPI`'s JSON-Schema
 * via the `definition` "WorkOrderPrefill".
 */
export interface WorkOrderPrefill {
  departmentId?: Departmentid16;
  description: Description6;
  guestName?: Guestname1;
  locationRef?: Locationref3;
  locationType: LocationType1;
  priority: Priority;
  sourceConversationId: Sourceconversationid3;
  sourceMessageId?: Sourcemessageid3;
  title: Title8;
  type: WorkOrderType;
}
