/**
 * The client's type surface. Import from here, never from `types.generated.ts`:
 * that file is overwritten by `npm run gen:types` and carries the document root
 * (`RelayAPI`), which is an artefact of the export, not a model.
 */
export type {
  AddParticipantsRequest, AgentStats, AnswerPatch, AssetIn, AssetOut, AssetPatch, AssetType, AuthorType,
  CategoryIn, CategoryOut, CategoryPatch, Channel,
  ChecklistAssignRequest, ChecklistCommentPatch, ChecklistInstanceOut, ChecklistInstanceQuery,
  ChecklistInstanceRowOut, ChecklistMissedQuery, ChecklistSchedule, ChecklistStatus,
  ChecklistTemplateIn, ChecklistTemplateOut, ChecklistTemplatePatch,
  ChecklistCategoryIn, ChecklistCategoryOut, ChecklistItemIn, ChecklistItemOut, ChecklistKind,
  ChecklistCategoryProgressOut, ChecklistLibraryCategoryOut, ChecklistLibraryEntryOut,
  ChecklistLibraryImport,
  ComplianceCycleOut, ComplianceOut,
  ComplianceRunsOut, ComplianceTemplateOut, ConversationDetail,
  ConversationPatch, ConversationStatus, ConversationSummary,
  CreateLogEntryRequest, CreateNoteRequest, CreateStaffConversationRequest, CreateStaffRequest, CreateWorkOrder, CycleOut, DayBucket,
  DeliveryStatus, DepartmentBucket, DepartmentIn, DepartmentOut,
  DepartmentPatch, DepartmentType, Direction, DraftPromptOut,
  DraftPromptStatus, GroupPatch, GuestDetail, GuestOut, GuestThread, GuestThreadMessage,
  HkAssignRequest, HkAssignmentOut, HkAssignmentStatus, HkBoardOut, HkEventOut,
  HkHousekeeperOut, HkInspectRequest, HkInspectionRowOut, HkMarkDirtyRequest, HkOccupancy,
  HkPhotoOut, HkReorderRequest, HkRoomDetailOut, HkRoomOut, HkServiceType, HkStatus,
  HkStatusRequest, HkSummaryOut,
  HourBucket, InspectRequest, InspectionRowOut, ListQuery, LocationType, LogEntryOut, LogFeedOut,
  LogFieldType, LogFieldValueIn, LogFieldValueOut, LogMentionableOut, LogTemplateFieldIn,
  LogTemplateFieldOut, LogTemplateIn, LogTemplateOut, LogTemplatePatch, LogTemplateRef,
  LoginRequest, MembershipOut,
  MessageOut, NoteOut, NotificationOut, Overview, PmCadence, PmCycleStatus, PmItemType, PmRunStatus,
  PmTemplateMode, PmUnitKind, PmUnitSource, PreviewRequest, Priority,
  PropertySettingsOut, PropertySettingsPatch, QuickReplyIn, QuickReplyOut,
  QuickReplyPatch, RenderRequest, RenderedQuickReply, ResponseBucket, Role, RoomEventType,
  RunAnswerOut, RunOut, RunPhotoOut,
  SendMessageRequest, SendStaffMessageRequest, SessionOut, Shift, SimEvent, SimGuest,
  SmsConsentStatus,
  StaffConversationDetail, StaffConversationKind, StaffConversationOut, StaffDirectoryEntryOut,
  StaffMessageOut, StaffParticipantOut, StaffPatch, StaffUserOut, StartRunRequest, StayOut, StayStatus,
  SweepCounts, SweepCycleOut, SweepOut, SweepRunBrief, SweepTemplateOut, SweepUnitOut,
  TemplateIn, TemplateItemIn, TemplateItemOut, TemplateOut, TemplatePatch,
  UnitImportError, UnitImportOut, UnitIn, UnitOut, UnitPatch, UnreadCount, UserOut,
  WorkOrderBrief, WorkOrderDetail, WorkOrderEventOut, WorkOrderEventType,
  WorkOrderListQuery, WorkOrderOut, WorkOrderPatch, WorkOrderPhotoKind,
  WorkOrderPhotoOut, WorkOrderPrefill, WorkOrderStatus, WorkOrderType,
} from './types.generated'
