"""init

Revision ID: 0001
Revises:
Create Date: 2026-09-10 15:30:42.574707

"""

import sqlalchemy as sa

import app.db
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("run_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "done",
                "failed",
                "dead",
                name="ck_enum_jobstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("locked_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("finished_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index("ix_job_status_run_at", ["status", "run_at"], unique=False)

    op.create_table(
        "pms_event",
        sa.Column("integration_key", sa.String(length=60), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "integration_key", "external_id", "event_type", name="uq_pms_event_idem"
        ),
    )
    op.create_table(
        "property",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("address", sa.String(length=400), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("sms_number", sa.String(length=32), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("primary_color", sa.String(length=16), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "user_account",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "disabled",
                name="ck_enum_userstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=200), nullable=True),
        sa.Column("last_seen_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("notification_prefs", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_log",
        sa.Column("property_id", sa.String(length=36), nullable=True),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["user_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_property_id"), ["property_id"], unique=False)

    op.create_table(
        "department",
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "front_desk",
                "housekeeping",
                "engineering",
                "food_beverage",
                "spa",
                "security",
                "valet",
                "other",
                name="ck_enum_departmenttype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("escalation_minutes", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("department", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_department_property_id"), ["property_id"], unique=False
        )

    op.create_table(
        "guest",
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("phone_e164", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("loyalty_program", sa.String(length=50), nullable=True),
        sa.Column("loyalty_tier", sa.String(length=50), nullable=True),
        sa.Column("loyalty_number", sa.String(length=50), nullable=True),
        sa.Column("vip", sa.Boolean(), nullable=False),
        sa.Column("pms_profile_id", sa.String(length=100), nullable=True),
        sa.Column(
            "sms_consent_status",
            sa.Enum(
                "unknown",
                "opted_in",
                "opted_out",
                name="ck_enum_smsconsentstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sms_consent_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("sms_consent_source", sa.String(length=50), nullable=True),
        sa.Column("notes_summary", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("property_id", "phone_e164", name="uq_guest_property_phone"),
    )
    with op.batch_alter_table("guest", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_guest_property_id"), ["property_id"], unique=False)

    op.create_table(
        "notification",
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=1000), nullable=True),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("read_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_property_id"), ["property_id"], unique=False
        )
        batch_op.create_index("ix_notification_user_read", ["user_id", "read_at"], unique=False)

    op.create_table(
        "resolution_category",
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["resolution_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resolution_category", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resolution_category_property_id"), ["property_id"], unique=False
        )

    op.create_table(
        "user_session",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("last_seen_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("user_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_session_user_id"), ["user_id"], unique=False)

    op.create_table(
        "digital_asset",
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "file",
                "link",
                "menu",
                "map",
                "form",
                name="ck_enum_assettype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("short_code", sa.String(length=16), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=1000), nullable=True),
        sa.Column("department_id", sa.String(length=36), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("valid_from", app.db.UTCDateTime(), nullable=True),
        sa.Column("valid_until", app.db.UTCDateTime(), nullable=True),
        sa.Column("send_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("short_code"),
    )
    with op.batch_alter_table("digital_asset", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_digital_asset_property_id"), ["property_id"], unique=False
        )

    op.create_table(
        "property_membership",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "agent",
                "dept_staff",
                "supervisor",
                "manager",
                "admin",
                "corporate",
                name="ck_enum_role",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("department_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "property_id", name="uq_membership_user_property"),
    )
    with op.batch_alter_table("property_membership", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_property_membership_property_id"), ["property_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_property_membership_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "quick_reply",
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("department_id", sa.String(length=36), nullable=True),
        sa.Column("shortcut", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("property_id", "shortcut", name="uq_quick_reply_shortcut"),
    )
    with op.batch_alter_table("quick_reply", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quick_reply_property_id"), ["property_id"], unique=False
        )

    op.create_table(
        "stay",
        sa.Column("guest_id", sa.String(length=36), nullable=False),
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("pms_reservation_id", sa.String(length=100), nullable=True),
        sa.Column("room_number", sa.String(length=10), nullable=True),
        sa.Column("room_type", sa.String(length=50), nullable=True),
        sa.Column("rate_code", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "reserved",
                "checked_in",
                "checked_out",
                "cancelled",
                "no_show",
                name="ck_enum_staystatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("arrival_date", sa.Date(), nullable=False),
        sa.Column("departure_date", sa.Date(), nullable=False),
        sa.Column("actual_checkin_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("actual_checkout_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("adults", sa.Integer(), nullable=False),
        sa.Column("children", sa.Integer(), nullable=False),
        sa.Column("group_code", sa.String(length=50), nullable=True),
        sa.Column("market_segment", sa.String(length=50), nullable=True),
        sa.Column("is_return_guest", sa.Boolean(), nullable=False),
        sa.Column("stay_count", sa.Integer(), nullable=False),
        sa.Column("raw_pms", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stay", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stay_guest_id"), ["guest_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_stay_pms_reservation_id"), ["pms_reservation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stay_property_id"), ["property_id"], unique=False)
        batch_op.create_index("ix_stay_property_status", ["property_id", "status"], unique=False)

    op.create_table(
        "conversation",
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("guest_id", sa.String(length=36), nullable=False),
        sa.Column("stay_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "snoozed",
                "archived",
                name="ck_enum_conversationstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("assigned_user_id", sa.String(length=36), nullable=True),
        sa.Column("assigned_department_id", sa.String(length=36), nullable=True),
        sa.Column(
            "channel_primary",
            sa.Enum(
                "sms",
                "web",
                "whatsapp",
                "email",
                name="ck_enum_channel",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("last_guest_message_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("last_staff_message_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("first_response_seconds", sa.Integer(), nullable=True),
        sa.Column("sla_due_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("sla_breach_notified_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("resolution_category_id", sa.String(length=36), nullable=True),
        sa.Column("snoozed_until", app.db.UTCDateTime(), nullable=True),
        sa.Column("archived_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["user_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolution_category_id"],
            ["resolution_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stay_id"],
            ["stay.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversation_guest_id"), ["guest_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_conversation_property_id"), ["property_id"], unique=False
        )
        batch_op.create_index(
            "ix_conversation_property_sla", ["property_id", "sla_due_at"], unique=False
        )
        batch_op.create_index(
            "ix_conversation_property_status", ["property_id", "status"], unique=False
        )

    op.create_table(
        "internal_note",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("author_user_id", sa.String(length=36), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("mentions", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["user_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("internal_note", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_internal_note_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_internal_note_property_id"), ["property_id"], unique=False
        )

    op.create_table(
        "message",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "inbound",
                "outbound",
                name="ck_enum_direction",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "author_type",
            sa.Enum(
                "guest",
                "staff",
                "system",
                "automation",
                name="ck_enum_authortype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("author_user_id", sa.String(length=36), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "sms",
                "web",
                "whatsapp",
                "email",
                name="ck_enum_channel",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column("digital_asset_id", sa.String(length=36), nullable=True),
        sa.Column(
            "delivery_status",
            sa.Enum(
                "queued",
                "sent",
                "delivered",
                "failed",
                "undelivered",
                name="ck_enum_deliverystatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider_message_id", sa.String(length=100), nullable=True),
        sa.Column("provider_error_code", sa.String(length=50), nullable=True),
        sa.Column("provider_error_message", sa.String(length=500), nullable=True),
        sa.Column("redacted", sa.Boolean(), nullable=False),
        sa.Column("sent_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("delivered_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["user_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["digital_asset_id"],
            ["digital_asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "property_id", "provider_message_id", name="uq_message_property_provider"
        ),
    )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_message_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            "ix_message_conversation_sent", ["conversation_id", "sent_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_message_property_id"), ["property_id"], unique=False)

    op.create_table(
        "work_order",
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "maintenance",
                "housekeeping",
                "guest_request",
                "pm",
                "other",
                name="ck_enum_workordertype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "normal",
                "high",
                "urgent",
                name="ck_enum_priority",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "assigned",
                "in_progress",
                "blocked",
                "complete",
                "verified",
                "cancelled",
                name="ck_enum_workorderstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "location_type",
            sa.Enum(
                "room",
                "public_area",
                "equipment",
                "other",
                name="ck_enum_locationtype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("location_ref", sa.String(length=100), nullable=True),
        sa.Column("department_id", sa.String(length=36), nullable=True),
        sa.Column("assigned_user_id", sa.String(length=36), nullable=True),
        sa.Column("reported_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("source_conversation_id", sa.String(length=36), nullable=True),
        sa.Column("source_message_id", sa.String(length=36), nullable=True),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column("due_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("started_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("completed_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("verified_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("guest_notified_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("acknowledged_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["user_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reported_by_user_id"],
            ["user_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_conversation_id"],
            ["conversation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("work_order", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_work_order_property_id"), ["property_id"], unique=False
        )
        batch_op.create_index(
            "ix_work_order_property_status", ["property_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_work_order_source_conversation_id"),
            ["source_conversation_id"],
            unique=False,
        )

    op.create_table(
        "draft_prompt",
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("work_order_id", sa.String(length=36), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "dismissed",
                name="ck_enum_draftpromptstatus",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("resolved_at", app.db.UTCDateTime(), nullable=True),
        sa.Column("resolved_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["user_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("draft_prompt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_draft_prompt_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_draft_prompt_property_id"), ["property_id"], unique=False
        )

    op.create_table(
        "work_order_event",
        sa.Column("work_order_id", sa.String(length=36), nullable=False),
        sa.Column("property_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "created",
                "status_changed",
                "assigned",
                "commented",
                "priority_changed",
                name="ck_enum_workordereventtype",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("from_value", sa.String(length=100), nullable=True),
        sa.Column("to_value", sa.String(length=100), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", app.db.UTCDateTime(), nullable=False),
        sa.Column("updated_at", app.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["property.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("work_order_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_work_order_event_property_id"), ["property_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_work_order_event_work_order_id"), ["work_order_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_order_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_work_order_event_work_order_id"))
        batch_op.drop_index(batch_op.f("ix_work_order_event_property_id"))

    op.drop_table("work_order_event")
    with op.batch_alter_table("draft_prompt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_draft_prompt_property_id"))
        batch_op.drop_index(batch_op.f("ix_draft_prompt_conversation_id"))

    op.drop_table("draft_prompt")
    with op.batch_alter_table("work_order", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_work_order_source_conversation_id"))
        batch_op.drop_index("ix_work_order_property_status")
        batch_op.drop_index(batch_op.f("ix_work_order_property_id"))

    op.drop_table("work_order")
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_property_id"))
        batch_op.drop_index("ix_message_conversation_sent")
        batch_op.drop_index(batch_op.f("ix_message_conversation_id"))

    op.drop_table("message")
    with op.batch_alter_table("internal_note", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_internal_note_property_id"))
        batch_op.drop_index(batch_op.f("ix_internal_note_conversation_id"))

    op.drop_table("internal_note")
    with op.batch_alter_table("conversation", schema=None) as batch_op:
        batch_op.drop_index("ix_conversation_property_status")
        batch_op.drop_index("ix_conversation_property_sla")
        batch_op.drop_index(batch_op.f("ix_conversation_property_id"))
        batch_op.drop_index(batch_op.f("ix_conversation_guest_id"))

    op.drop_table("conversation")
    with op.batch_alter_table("stay", schema=None) as batch_op:
        batch_op.drop_index("ix_stay_property_status")
        batch_op.drop_index(batch_op.f("ix_stay_property_id"))
        batch_op.drop_index(batch_op.f("ix_stay_pms_reservation_id"))
        batch_op.drop_index(batch_op.f("ix_stay_guest_id"))

    op.drop_table("stay")
    with op.batch_alter_table("quick_reply", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quick_reply_property_id"))

    op.drop_table("quick_reply")
    with op.batch_alter_table("property_membership", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_property_membership_user_id"))
        batch_op.drop_index(batch_op.f("ix_property_membership_property_id"))

    op.drop_table("property_membership")
    with op.batch_alter_table("digital_asset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_digital_asset_property_id"))

    op.drop_table("digital_asset")
    with op.batch_alter_table("user_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_session_user_id"))

    op.drop_table("user_session")
    with op.batch_alter_table("resolution_category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resolution_category_property_id"))

    op.drop_table("resolution_category")
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_index("ix_notification_user_read")
        batch_op.drop_index(batch_op.f("ix_notification_property_id"))

    op.drop_table("notification")
    with op.batch_alter_table("guest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guest_property_id"))

    op.drop_table("guest")
    with op.batch_alter_table("department", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_department_property_id"))

    op.drop_table("department")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_property_id"))

    op.drop_table("audit_log")
    op.drop_table("user_account")
    op.drop_table("property")
    op.drop_table("pms_event")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("ix_job_status_run_at")

    op.drop_table("job")
    # ### end Alembic commands ###
