"""add stay unique reservation

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-10 20:26:33.586040

"""

from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stay", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_stay_property_reservation", ["property_id", "pms_reservation_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stay", schema=None) as batch_op:
        batch_op.drop_constraint("uq_stay_property_reservation", type_="unique")

    # ### end Alembic commands ###
